#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceGR2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBTRANS")]
	public partial class DBTRANSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBTrans_PostGISerial(TBTrans_PostGISerial instance);
    partial void UpdateTBTrans_PostGISerial(TBTrans_PostGISerial instance);
    partial void DeleteTBTrans_PostGISerial(TBTrans_PostGISerial instance);
    partial void InsertTBTrans_GR_LOG(TBTrans_GR_LOG instance);
    partial void UpdateTBTrans_GR_LOG(TBTrans_GR_LOG instance);
    partial void DeleteTBTrans_GR_LOG(TBTrans_GR_LOG instance);
    partial void InsertTBTrans_PostGRItem(TBTrans_PostGRItem instance);
    partial void UpdateTBTrans_PostGRItem(TBTrans_PostGRItem instance);
    partial void DeleteTBTrans_PostGRItem(TBTrans_PostGRItem instance);
    #endregion
		
		public DBTRANSDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DBTRANSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBTRANSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTRANSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTRANSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBTRANSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBTrans_PostGISerial> TBTrans_PostGISerials
		{
			get
			{
				return this.GetTable<TBTrans_PostGISerial>();
			}
		}
		
		public System.Data.Linq.Table<TBTrans_GR_LOG> TBTrans_GR_LOGs
		{
			get
			{
				return this.GetTable<TBTrans_GR_LOG>();
			}
		}
		
		public System.Data.Linq.Table<TBTrans_PostGRItem> TBTrans_PostGRItems
		{
			get
			{
				return this.GetTable<TBTrans_PostGRItem>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBTrans_PostGISerial")]
	public partial class TBTrans_PostGISerial : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DELIV_NUMB;
		
		private string _SERIALNO;
		
		private string _ITM_NUMBER;
		
		private string _MATNR;
		
		private System.Nullable<int> _SAVE_SAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDELIV_NUMBChanging(string value);
    partial void OnDELIV_NUMBChanged();
    partial void OnSERIALNOChanging(string value);
    partial void OnSERIALNOChanged();
    partial void OnITM_NUMBERChanging(string value);
    partial void OnITM_NUMBERChanged();
    partial void OnMATNRChanging(string value);
    partial void OnMATNRChanged();
    partial void OnSAVE_SAPChanging(System.Nullable<int> value);
    partial void OnSAVE_SAPChanged();
    #endregion
		
		public TBTrans_PostGISerial()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DELIV_NUMB", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DELIV_NUMB
		{
			get
			{
				return this._DELIV_NUMB;
			}
			set
			{
				if ((this._DELIV_NUMB != value))
				{
					this.OnDELIV_NUMBChanging(value);
					this.SendPropertyChanging();
					this._DELIV_NUMB = value;
					this.SendPropertyChanged("DELIV_NUMB");
					this.OnDELIV_NUMBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIALNO", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SERIALNO
		{
			get
			{
				return this._SERIALNO;
			}
			set
			{
				if ((this._SERIALNO != value))
				{
					this.OnSERIALNOChanging(value);
					this.SendPropertyChanging();
					this._SERIALNO = value;
					this.SendPropertyChanged("SERIALNO");
					this.OnSERIALNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITM_NUMBER", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ITM_NUMBER
		{
			get
			{
				return this._ITM_NUMBER;
			}
			set
			{
				if ((this._ITM_NUMBER != value))
				{
					this.OnITM_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._ITM_NUMBER = value;
					this.SendPropertyChanged("ITM_NUMBER");
					this.OnITM_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATNR", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATNR
		{
			get
			{
				return this._MATNR;
			}
			set
			{
				if ((this._MATNR != value))
				{
					this.OnMATNRChanging(value);
					this.SendPropertyChanging();
					this._MATNR = value;
					this.SendPropertyChanged("MATNR");
					this.OnMATNRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVE_SAP", DbType="Int")]
		public System.Nullable<int> SAVE_SAP
		{
			get
			{
				return this._SAVE_SAP;
			}
			set
			{
				if ((this._SAVE_SAP != value))
				{
					this.OnSAVE_SAPChanging(value);
					this.SendPropertyChanging();
					this._SAVE_SAP = value;
					this.SendPropertyChanged("SAVE_SAP");
					this.OnSAVE_SAPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBTrans_GR_LOG")]
	public partial class TBTrans_GR_LOG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _p_P_RPOINT;
		
		private string _IN_COUNT;
		
		private string _IN_COUNT_SER;
		
		private string _O_MSG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onp_P_RPOINTChanging(string value);
    partial void Onp_P_RPOINTChanged();
    partial void OnIN_COUNTChanging(string value);
    partial void OnIN_COUNTChanged();
    partial void OnIN_COUNT_SERChanging(string value);
    partial void OnIN_COUNT_SERChanged();
    partial void OnO_MSGChanging(string value);
    partial void OnO_MSGChanged();
    #endregion
		
		public TBTrans_GR_LOG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_P_RPOINT", DbType="VarChar(2)")]
		public string p_P_RPOINT
		{
			get
			{
				return this._p_P_RPOINT;
			}
			set
			{
				if ((this._p_P_RPOINT != value))
				{
					this.Onp_P_RPOINTChanging(value);
					this.SendPropertyChanging();
					this._p_P_RPOINT = value;
					this.SendPropertyChanged("p_P_RPOINT");
					this.Onp_P_RPOINTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IN_COUNT", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string IN_COUNT
		{
			get
			{
				return this._IN_COUNT;
			}
			set
			{
				if ((this._IN_COUNT != value))
				{
					this.OnIN_COUNTChanging(value);
					this.SendPropertyChanging();
					this._IN_COUNT = value;
					this.SendPropertyChanged("IN_COUNT");
					this.OnIN_COUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IN_COUNT_SER", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string IN_COUNT_SER
		{
			get
			{
				return this._IN_COUNT_SER;
			}
			set
			{
				if ((this._IN_COUNT_SER != value))
				{
					this.OnIN_COUNT_SERChanging(value);
					this.SendPropertyChanging();
					this._IN_COUNT_SER = value;
					this.SendPropertyChanged("IN_COUNT_SER");
					this.OnIN_COUNT_SERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_MSG", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string O_MSG
		{
			get
			{
				return this._O_MSG;
			}
			set
			{
				if ((this._O_MSG != value))
				{
					this.OnO_MSGChanging(value);
					this.SendPropertyChanging();
					this._O_MSG = value;
					this.SendPropertyChanged("O_MSG");
					this.OnO_MSGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBTrans_PostGRItem")]
	public partial class TBTrans_PostGRItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _VBELN;
		
		private string _MATNR;
		
		private string _MAKTX;
		
		private System.Nullable<int> _LFIMG;
		
		private string _VRKME;
		
		private string _WERKS;
		
		private string _LGORT;
		
		private System.Nullable<System.DateTime> _ERDAT;
		
		private string _SERNP;
		
		private string _XCHPF;
		
		private string _MHDRZ;
		
		private string _MHDHB;
		
		private System.Nullable<int> _STATUS;
		
		private System.Nullable<int> _QTY;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
		private string _DOC_SEARCH;
		
		private string _DOC_TYPE;
		
		private string _DOC_SITE;
		
		private System.Nullable<System.DateTime> _DOC_DATE;
		
		private string _EMP_ID;
		
		private string _POSNR;
		
		private System.Nullable<int> _RFMNG;
		
		private string _LGMNG;
		
		private string _MEINS;
		
		private string _UMVKZ;
		
		private string _BWART;
		
		private string _SERIAL;
		
		private string _PKSTK;
		
		private string _WBSTK;
		
		private string _KOSTK;
		
		private string _VSBED;
		
		private string _LFART;
		
		private string _BEZEI;
		
		private string _VSART;
		
		private string _VGBEL;
		
		private string _CHARG;
		
		private string _UNIT_SELECT;
		
		private string _BATCH_CHECK;
		
		private System.Nullable<System.DateTime> _BATCH_EXP_DATE;
		
		private System.Nullable<System.DateTime> _BATCH_MANUFAC_DATE;
		
		private string _UECHA;
		
		private string _KCMENG;
		
		private string _SPLIT;
		
		private System.Nullable<double> _WEIGHTS;
		
		private System.Nullable<int> _QTY_D;
		
		private string _EMP_CONFIRM_DAM;
		
		private string _VGPOS;
		
		private string _HH_DOCNO;
		
		private string _SAP_DOCNO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVBELNChanging(string value);
    partial void OnVBELNChanged();
    partial void OnMATNRChanging(string value);
    partial void OnMATNRChanged();
    partial void OnMAKTXChanging(string value);
    partial void OnMAKTXChanged();
    partial void OnLFIMGChanging(System.Nullable<int> value);
    partial void OnLFIMGChanged();
    partial void OnVRKMEChanging(string value);
    partial void OnVRKMEChanged();
    partial void OnWERKSChanging(string value);
    partial void OnWERKSChanged();
    partial void OnLGORTChanging(string value);
    partial void OnLGORTChanged();
    partial void OnERDATChanging(System.Nullable<System.DateTime> value);
    partial void OnERDATChanged();
    partial void OnSERNPChanging(string value);
    partial void OnSERNPChanged();
    partial void OnXCHPFChanging(string value);
    partial void OnXCHPFChanged();
    partial void OnMHDRZChanging(string value);
    partial void OnMHDRZChanged();
    partial void OnMHDHBChanging(string value);
    partial void OnMHDHBChanged();
    partial void OnSTATUSChanging(System.Nullable<int> value);
    partial void OnSTATUSChanged();
    partial void OnQTYChanging(System.Nullable<int> value);
    partial void OnQTYChanged();
    partial void OnCREATEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATEDATEChanged();
    partial void OnDOC_SEARCHChanging(string value);
    partial void OnDOC_SEARCHChanged();
    partial void OnDOC_TYPEChanging(string value);
    partial void OnDOC_TYPEChanged();
    partial void OnDOC_SITEChanging(string value);
    partial void OnDOC_SITEChanged();
    partial void OnDOC_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDOC_DATEChanged();
    partial void OnEMP_IDChanging(string value);
    partial void OnEMP_IDChanged();
    partial void OnPOSNRChanging(string value);
    partial void OnPOSNRChanged();
    partial void OnRFMNGChanging(System.Nullable<int> value);
    partial void OnRFMNGChanged();
    partial void OnLGMNGChanging(string value);
    partial void OnLGMNGChanged();
    partial void OnMEINSChanging(string value);
    partial void OnMEINSChanged();
    partial void OnUMVKZChanging(string value);
    partial void OnUMVKZChanged();
    partial void OnBWARTChanging(string value);
    partial void OnBWARTChanged();
    partial void OnSERIALChanging(string value);
    partial void OnSERIALChanged();
    partial void OnPKSTKChanging(string value);
    partial void OnPKSTKChanged();
    partial void OnWBSTKChanging(string value);
    partial void OnWBSTKChanged();
    partial void OnKOSTKChanging(string value);
    partial void OnKOSTKChanged();
    partial void OnVSBEDChanging(string value);
    partial void OnVSBEDChanged();
    partial void OnLFARTChanging(string value);
    partial void OnLFARTChanged();
    partial void OnBEZEIChanging(string value);
    partial void OnBEZEIChanged();
    partial void OnVSARTChanging(string value);
    partial void OnVSARTChanged();
    partial void OnVGBELChanging(string value);
    partial void OnVGBELChanged();
    partial void OnCHARGChanging(string value);
    partial void OnCHARGChanged();
    partial void OnUNIT_SELECTChanging(string value);
    partial void OnUNIT_SELECTChanged();
    partial void OnBATCH_CHECKChanging(string value);
    partial void OnBATCH_CHECKChanged();
    partial void OnBATCH_EXP_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnBATCH_EXP_DATEChanged();
    partial void OnBATCH_MANUFAC_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnBATCH_MANUFAC_DATEChanged();
    partial void OnUECHAChanging(string value);
    partial void OnUECHAChanged();
    partial void OnKCMENGChanging(string value);
    partial void OnKCMENGChanged();
    partial void OnSPLITChanging(string value);
    partial void OnSPLITChanged();
    partial void OnWEIGHTSChanging(System.Nullable<double> value);
    partial void OnWEIGHTSChanged();
    partial void OnQTY_DChanging(System.Nullable<int> value);
    partial void OnQTY_DChanged();
    partial void OnEMP_CONFIRM_DAMChanging(string value);
    partial void OnEMP_CONFIRM_DAMChanged();
    partial void OnVGPOSChanging(string value);
    partial void OnVGPOSChanged();
    partial void OnHH_DOCNOChanging(string value);
    partial void OnHH_DOCNOChanged();
    partial void OnSAP_DOCNOChanging(string value);
    partial void OnSAP_DOCNOChanged();
    #endregion
		
		public TBTrans_PostGRItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VBELN", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string VBELN
		{
			get
			{
				return this._VBELN;
			}
			set
			{
				if ((this._VBELN != value))
				{
					this.OnVBELNChanging(value);
					this.SendPropertyChanging();
					this._VBELN = value;
					this.SendPropertyChanged("VBELN");
					this.OnVBELNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATNR", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATNR
		{
			get
			{
				return this._MATNR;
			}
			set
			{
				if ((this._MATNR != value))
				{
					this.OnMATNRChanging(value);
					this.SendPropertyChanging();
					this._MATNR = value;
					this.SendPropertyChanged("MATNR");
					this.OnMATNRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKTX", DbType="VarChar(50)")]
		public string MAKTX
		{
			get
			{
				return this._MAKTX;
			}
			set
			{
				if ((this._MAKTX != value))
				{
					this.OnMAKTXChanging(value);
					this.SendPropertyChanging();
					this._MAKTX = value;
					this.SendPropertyChanged("MAKTX");
					this.OnMAKTXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LFIMG", DbType="Int")]
		public System.Nullable<int> LFIMG
		{
			get
			{
				return this._LFIMG;
			}
			set
			{
				if ((this._LFIMG != value))
				{
					this.OnLFIMGChanging(value);
					this.SendPropertyChanging();
					this._LFIMG = value;
					this.SendPropertyChanged("LFIMG");
					this.OnLFIMGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VRKME", DbType="VarChar(50)")]
		public string VRKME
		{
			get
			{
				return this._VRKME;
			}
			set
			{
				if ((this._VRKME != value))
				{
					this.OnVRKMEChanging(value);
					this.SendPropertyChanging();
					this._VRKME = value;
					this.SendPropertyChanged("VRKME");
					this.OnVRKMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WERKS", DbType="VarChar(50)")]
		public string WERKS
		{
			get
			{
				return this._WERKS;
			}
			set
			{
				if ((this._WERKS != value))
				{
					this.OnWERKSChanging(value);
					this.SendPropertyChanging();
					this._WERKS = value;
					this.SendPropertyChanged("WERKS");
					this.OnWERKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LGORT", DbType="VarChar(50)")]
		public string LGORT
		{
			get
			{
				return this._LGORT;
			}
			set
			{
				if ((this._LGORT != value))
				{
					this.OnLGORTChanging(value);
					this.SendPropertyChanging();
					this._LGORT = value;
					this.SendPropertyChanged("LGORT");
					this.OnLGORTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ERDAT", DbType="DateTime")]
		public System.Nullable<System.DateTime> ERDAT
		{
			get
			{
				return this._ERDAT;
			}
			set
			{
				if ((this._ERDAT != value))
				{
					this.OnERDATChanging(value);
					this.SendPropertyChanging();
					this._ERDAT = value;
					this.SendPropertyChanged("ERDAT");
					this.OnERDATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERNP", DbType="VarChar(50)")]
		public string SERNP
		{
			get
			{
				return this._SERNP;
			}
			set
			{
				if ((this._SERNP != value))
				{
					this.OnSERNPChanging(value);
					this.SendPropertyChanging();
					this._SERNP = value;
					this.SendPropertyChanged("SERNP");
					this.OnSERNPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XCHPF", DbType="VarChar(1)")]
		public string XCHPF
		{
			get
			{
				return this._XCHPF;
			}
			set
			{
				if ((this._XCHPF != value))
				{
					this.OnXCHPFChanging(value);
					this.SendPropertyChanging();
					this._XCHPF = value;
					this.SendPropertyChanged("XCHPF");
					this.OnXCHPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MHDRZ", DbType="VarChar(50)")]
		public string MHDRZ
		{
			get
			{
				return this._MHDRZ;
			}
			set
			{
				if ((this._MHDRZ != value))
				{
					this.OnMHDRZChanging(value);
					this.SendPropertyChanging();
					this._MHDRZ = value;
					this.SendPropertyChanged("MHDRZ");
					this.OnMHDRZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MHDHB", DbType="VarChar(50)")]
		public string MHDHB
		{
			get
			{
				return this._MHDHB;
			}
			set
			{
				if ((this._MHDHB != value))
				{
					this.OnMHDHBChanging(value);
					this.SendPropertyChanging();
					this._MHDHB = value;
					this.SendPropertyChanged("MHDHB");
					this.OnMHDHBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Int")]
		public System.Nullable<int> QTY
		{
			get
			{
				return this._QTY;
			}
			set
			{
				if ((this._QTY != value))
				{
					this.OnQTYChanging(value);
					this.SendPropertyChanging();
					this._QTY = value;
					this.SendPropertyChanged("QTY");
					this.OnQTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this.OnCREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE = value;
					this.SendPropertyChanged("CREATEDATE");
					this.OnCREATEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC_SEARCH", DbType="VarChar(50)")]
		public string DOC_SEARCH
		{
			get
			{
				return this._DOC_SEARCH;
			}
			set
			{
				if ((this._DOC_SEARCH != value))
				{
					this.OnDOC_SEARCHChanging(value);
					this.SendPropertyChanging();
					this._DOC_SEARCH = value;
					this.SendPropertyChanged("DOC_SEARCH");
					this.OnDOC_SEARCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC_TYPE", DbType="VarChar(50)")]
		public string DOC_TYPE
		{
			get
			{
				return this._DOC_TYPE;
			}
			set
			{
				if ((this._DOC_TYPE != value))
				{
					this.OnDOC_TYPEChanging(value);
					this.SendPropertyChanging();
					this._DOC_TYPE = value;
					this.SendPropertyChanged("DOC_TYPE");
					this.OnDOC_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC_SITE", DbType="VarChar(50)")]
		public string DOC_SITE
		{
			get
			{
				return this._DOC_SITE;
			}
			set
			{
				if ((this._DOC_SITE != value))
				{
					this.OnDOC_SITEChanging(value);
					this.SendPropertyChanging();
					this._DOC_SITE = value;
					this.SendPropertyChanged("DOC_SITE");
					this.OnDOC_SITEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOC_DATE
		{
			get
			{
				return this._DOC_DATE;
			}
			set
			{
				if ((this._DOC_DATE != value))
				{
					this.OnDOC_DATEChanging(value);
					this.SendPropertyChanging();
					this._DOC_DATE = value;
					this.SendPropertyChanged("DOC_DATE");
					this.OnDOC_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string EMP_ID
		{
			get
			{
				return this._EMP_ID;
			}
			set
			{
				if ((this._EMP_ID != value))
				{
					this.OnEMP_IDChanging(value);
					this.SendPropertyChanging();
					this._EMP_ID = value;
					this.SendPropertyChanged("EMP_ID");
					this.OnEMP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSNR", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string POSNR
		{
			get
			{
				return this._POSNR;
			}
			set
			{
				if ((this._POSNR != value))
				{
					this.OnPOSNRChanging(value);
					this.SendPropertyChanging();
					this._POSNR = value;
					this.SendPropertyChanged("POSNR");
					this.OnPOSNRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFMNG", DbType="Int")]
		public System.Nullable<int> RFMNG
		{
			get
			{
				return this._RFMNG;
			}
			set
			{
				if ((this._RFMNG != value))
				{
					this.OnRFMNGChanging(value);
					this.SendPropertyChanging();
					this._RFMNG = value;
					this.SendPropertyChanged("RFMNG");
					this.OnRFMNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LGMNG", DbType="VarChar(50)")]
		public string LGMNG
		{
			get
			{
				return this._LGMNG;
			}
			set
			{
				if ((this._LGMNG != value))
				{
					this.OnLGMNGChanging(value);
					this.SendPropertyChanging();
					this._LGMNG = value;
					this.SendPropertyChanged("LGMNG");
					this.OnLGMNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEINS", DbType="VarChar(50)")]
		public string MEINS
		{
			get
			{
				return this._MEINS;
			}
			set
			{
				if ((this._MEINS != value))
				{
					this.OnMEINSChanging(value);
					this.SendPropertyChanging();
					this._MEINS = value;
					this.SendPropertyChanged("MEINS");
					this.OnMEINSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UMVKZ", DbType="VarChar(50)")]
		public string UMVKZ
		{
			get
			{
				return this._UMVKZ;
			}
			set
			{
				if ((this._UMVKZ != value))
				{
					this.OnUMVKZChanging(value);
					this.SendPropertyChanging();
					this._UMVKZ = value;
					this.SendPropertyChanged("UMVKZ");
					this.OnUMVKZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BWART", DbType="VarChar(50)")]
		public string BWART
		{
			get
			{
				return this._BWART;
			}
			set
			{
				if ((this._BWART != value))
				{
					this.OnBWARTChanging(value);
					this.SendPropertyChanging();
					this._BWART = value;
					this.SendPropertyChanged("BWART");
					this.OnBWARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIAL", DbType="VarChar(50)")]
		public string SERIAL
		{
			get
			{
				return this._SERIAL;
			}
			set
			{
				if ((this._SERIAL != value))
				{
					this.OnSERIALChanging(value);
					this.SendPropertyChanging();
					this._SERIAL = value;
					this.SendPropertyChanged("SERIAL");
					this.OnSERIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKSTK", DbType="VarChar(50)")]
		public string PKSTK
		{
			get
			{
				return this._PKSTK;
			}
			set
			{
				if ((this._PKSTK != value))
				{
					this.OnPKSTKChanging(value);
					this.SendPropertyChanging();
					this._PKSTK = value;
					this.SendPropertyChanged("PKSTK");
					this.OnPKSTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WBSTK", DbType="VarChar(50)")]
		public string WBSTK
		{
			get
			{
				return this._WBSTK;
			}
			set
			{
				if ((this._WBSTK != value))
				{
					this.OnWBSTKChanging(value);
					this.SendPropertyChanging();
					this._WBSTK = value;
					this.SendPropertyChanged("WBSTK");
					this.OnWBSTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOSTK", DbType="VarChar(50)")]
		public string KOSTK
		{
			get
			{
				return this._KOSTK;
			}
			set
			{
				if ((this._KOSTK != value))
				{
					this.OnKOSTKChanging(value);
					this.SendPropertyChanging();
					this._KOSTK = value;
					this.SendPropertyChanged("KOSTK");
					this.OnKOSTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VSBED", DbType="VarChar(50)")]
		public string VSBED
		{
			get
			{
				return this._VSBED;
			}
			set
			{
				if ((this._VSBED != value))
				{
					this.OnVSBEDChanging(value);
					this.SendPropertyChanging();
					this._VSBED = value;
					this.SendPropertyChanged("VSBED");
					this.OnVSBEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LFART", DbType="VarChar(50)")]
		public string LFART
		{
			get
			{
				return this._LFART;
			}
			set
			{
				if ((this._LFART != value))
				{
					this.OnLFARTChanging(value);
					this.SendPropertyChanging();
					this._LFART = value;
					this.SendPropertyChanged("LFART");
					this.OnLFARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEZEI", DbType="VarChar(50)")]
		public string BEZEI
		{
			get
			{
				return this._BEZEI;
			}
			set
			{
				if ((this._BEZEI != value))
				{
					this.OnBEZEIChanging(value);
					this.SendPropertyChanging();
					this._BEZEI = value;
					this.SendPropertyChanged("BEZEI");
					this.OnBEZEIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VSART", DbType="VarChar(50)")]
		public string VSART
		{
			get
			{
				return this._VSART;
			}
			set
			{
				if ((this._VSART != value))
				{
					this.OnVSARTChanging(value);
					this.SendPropertyChanging();
					this._VSART = value;
					this.SendPropertyChanged("VSART");
					this.OnVSARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VGBEL", DbType="VarChar(50)")]
		public string VGBEL
		{
			get
			{
				return this._VGBEL;
			}
			set
			{
				if ((this._VGBEL != value))
				{
					this.OnVGBELChanging(value);
					this.SendPropertyChanging();
					this._VGBEL = value;
					this.SendPropertyChanged("VGBEL");
					this.OnVGBELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHARG", DbType="VarChar(50)")]
		public string CHARG
		{
			get
			{
				return this._CHARG;
			}
			set
			{
				if ((this._CHARG != value))
				{
					this.OnCHARGChanging(value);
					this.SendPropertyChanging();
					this._CHARG = value;
					this.SendPropertyChanged("CHARG");
					this.OnCHARGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_SELECT", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UNIT_SELECT
		{
			get
			{
				return this._UNIT_SELECT;
			}
			set
			{
				if ((this._UNIT_SELECT != value))
				{
					this.OnUNIT_SELECTChanging(value);
					this.SendPropertyChanging();
					this._UNIT_SELECT = value;
					this.SendPropertyChanged("UNIT_SELECT");
					this.OnUNIT_SELECTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BATCH_CHECK", DbType="VarChar(50)")]
		public string BATCH_CHECK
		{
			get
			{
				return this._BATCH_CHECK;
			}
			set
			{
				if ((this._BATCH_CHECK != value))
				{
					this.OnBATCH_CHECKChanging(value);
					this.SendPropertyChanging();
					this._BATCH_CHECK = value;
					this.SendPropertyChanged("BATCH_CHECK");
					this.OnBATCH_CHECKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BATCH_EXP_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> BATCH_EXP_DATE
		{
			get
			{
				return this._BATCH_EXP_DATE;
			}
			set
			{
				if ((this._BATCH_EXP_DATE != value))
				{
					this.OnBATCH_EXP_DATEChanging(value);
					this.SendPropertyChanging();
					this._BATCH_EXP_DATE = value;
					this.SendPropertyChanged("BATCH_EXP_DATE");
					this.OnBATCH_EXP_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BATCH_MANUFAC_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> BATCH_MANUFAC_DATE
		{
			get
			{
				return this._BATCH_MANUFAC_DATE;
			}
			set
			{
				if ((this._BATCH_MANUFAC_DATE != value))
				{
					this.OnBATCH_MANUFAC_DATEChanging(value);
					this.SendPropertyChanging();
					this._BATCH_MANUFAC_DATE = value;
					this.SendPropertyChanged("BATCH_MANUFAC_DATE");
					this.OnBATCH_MANUFAC_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UECHA", DbType="VarChar(50)")]
		public string UECHA
		{
			get
			{
				return this._UECHA;
			}
			set
			{
				if ((this._UECHA != value))
				{
					this.OnUECHAChanging(value);
					this.SendPropertyChanging();
					this._UECHA = value;
					this.SendPropertyChanged("UECHA");
					this.OnUECHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KCMENG", DbType="VarChar(50)")]
		public string KCMENG
		{
			get
			{
				return this._KCMENG;
			}
			set
			{
				if ((this._KCMENG != value))
				{
					this.OnKCMENGChanging(value);
					this.SendPropertyChanging();
					this._KCMENG = value;
					this.SendPropertyChanged("KCMENG");
					this.OnKCMENGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPLIT", DbType="VarChar(50)")]
		public string SPLIT
		{
			get
			{
				return this._SPLIT;
			}
			set
			{
				if ((this._SPLIT != value))
				{
					this.OnSPLITChanging(value);
					this.SendPropertyChanging();
					this._SPLIT = value;
					this.SendPropertyChanged("SPLIT");
					this.OnSPLITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEIGHTS", DbType="Float")]
		public System.Nullable<double> WEIGHTS
		{
			get
			{
				return this._WEIGHTS;
			}
			set
			{
				if ((this._WEIGHTS != value))
				{
					this.OnWEIGHTSChanging(value);
					this.SendPropertyChanging();
					this._WEIGHTS = value;
					this.SendPropertyChanged("WEIGHTS");
					this.OnWEIGHTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY_D", DbType="Int")]
		public System.Nullable<int> QTY_D
		{
			get
			{
				return this._QTY_D;
			}
			set
			{
				if ((this._QTY_D != value))
				{
					this.OnQTY_DChanging(value);
					this.SendPropertyChanging();
					this._QTY_D = value;
					this.SendPropertyChanged("QTY_D");
					this.OnQTY_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_CONFIRM_DAM", DbType="VarChar(50)")]
		public string EMP_CONFIRM_DAM
		{
			get
			{
				return this._EMP_CONFIRM_DAM;
			}
			set
			{
				if ((this._EMP_CONFIRM_DAM != value))
				{
					this.OnEMP_CONFIRM_DAMChanging(value);
					this.SendPropertyChanging();
					this._EMP_CONFIRM_DAM = value;
					this.SendPropertyChanged("EMP_CONFIRM_DAM");
					this.OnEMP_CONFIRM_DAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VGPOS", DbType="VarChar(15)")]
		public string VGPOS
		{
			get
			{
				return this._VGPOS;
			}
			set
			{
				if ((this._VGPOS != value))
				{
					this.OnVGPOSChanging(value);
					this.SendPropertyChanging();
					this._VGPOS = value;
					this.SendPropertyChanged("VGPOS");
					this.OnVGPOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HH_DOCNO", DbType="VarChar(100)")]
		public string HH_DOCNO
		{
			get
			{
				return this._HH_DOCNO;
			}
			set
			{
				if ((this._HH_DOCNO != value))
				{
					this.OnHH_DOCNOChanging(value);
					this.SendPropertyChanging();
					this._HH_DOCNO = value;
					this.SendPropertyChanged("HH_DOCNO");
					this.OnHH_DOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAP_DOCNO", DbType="VarChar(100)")]
		public string SAP_DOCNO
		{
			get
			{
				return this._SAP_DOCNO;
			}
			set
			{
				if ((this._SAP_DOCNO != value))
				{
					this.OnSAP_DOCNOChanging(value);
					this.SendPropertyChanging();
					this._SAP_DOCNO = value;
					this.SendPropertyChanged("SAP_DOCNO");
					this.OnSAP_DOCNOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
