#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceGR2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBMASTER")]
	public partial class DBMASTERDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBMaster_Barcode(TBMaster_Barcode instance);
    partial void UpdateTBMaster_Barcode(TBMaster_Barcode instance);
    partial void DeleteTBMaster_Barcode(TBMaster_Barcode instance);
    #endregion
		
		public DBMASTERDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DBMASTERConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBMASTERDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMASTERDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMASTERDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMASTERDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBMaster_Barcode> TBMaster_Barcodes
		{
			get
			{
				return this.GetTable<TBMaster_Barcode>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBMaster_Barcode")]
	public partial class TBMaster_Barcode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PRODUCTCODE;
		
		private string _UNITCODE;
		
		private string _BARCODE;
		
		private short _STATUS;
		
		private System.DateTime _LAST_UPDATE_DATE;
		
		private System.DateTime _LAST_UPDATE_TIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPRODUCTCODEChanging(string value);
    partial void OnPRODUCTCODEChanged();
    partial void OnUNITCODEChanging(string value);
    partial void OnUNITCODEChanged();
    partial void OnBARCODEChanging(string value);
    partial void OnBARCODEChanged();
    partial void OnSTATUSChanging(short value);
    partial void OnSTATUSChanged();
    partial void OnLAST_UPDATE_DATEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_DATEChanged();
    partial void OnLAST_UPDATE_TIMEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_TIMEChanged();
    #endregion
		
		public TBMaster_Barcode()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PRODUCTCODE
		{
			get
			{
				return this._PRODUCTCODE;
			}
			set
			{
				if ((this._PRODUCTCODE != value))
				{
					this.OnPRODUCTCODEChanging(value);
					this.SendPropertyChanging();
					this._PRODUCTCODE = value;
					this.SendPropertyChanged("PRODUCTCODE");
					this.OnPRODUCTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string UNITCODE
		{
			get
			{
				return this._UNITCODE;
			}
			set
			{
				if ((this._UNITCODE != value))
				{
					this.OnUNITCODEChanging(value);
					this.SendPropertyChanging();
					this._UNITCODE = value;
					this.SendPropertyChanged("UNITCODE");
					this.OnUNITCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BARCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BARCODE
		{
			get
			{
				return this._BARCODE;
			}
			set
			{
				if ((this._BARCODE != value))
				{
					this.OnBARCODEChanging(value);
					this.SendPropertyChanging();
					this._BARCODE = value;
					this.SendPropertyChanged("BARCODE");
					this.OnBARCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="SmallInt NOT NULL")]
		public short STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_DATE
		{
			get
			{
				return this._LAST_UPDATE_DATE;
			}
			set
			{
				if ((this._LAST_UPDATE_DATE != value))
				{
					this.OnLAST_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_DATE = value;
					this.SendPropertyChanged("LAST_UPDATE_DATE");
					this.OnLAST_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_TIME
		{
			get
			{
				return this._LAST_UPDATE_TIME;
			}
			set
			{
				if ((this._LAST_UPDATE_TIME != value))
				{
					this.OnLAST_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_TIME = value;
					this.SendPropertyChanged("LAST_UPDATE_TIME");
					this.OnLAST_UPDATE_TIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
