#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webservice_DohomeApplication
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBMASTER")]
	public partial class DBMASTERDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBMaster_DHApp_User(TBMaster_DHApp_User instance);
    partial void UpdateTBMaster_DHApp_User(TBMaster_DHApp_User instance);
    partial void DeleteTBMaster_DHApp_User(TBMaster_DHApp_User instance);
    partial void InsertTBMaster_DHApp_Group_Policy(TBMaster_DHApp_Group_Policy instance);
    partial void UpdateTBMaster_DHApp_Group_Policy(TBMaster_DHApp_Group_Policy instance);
    partial void DeleteTBMaster_DHApp_Group_Policy(TBMaster_DHApp_Group_Policy instance);
    partial void InsertTBMaster_Site(TBMaster_Site instance);
    partial void UpdateTBMaster_Site(TBMaster_Site instance);
    partial void DeleteTBMaster_Site(TBMaster_Site instance);
    partial void InsertTBMaster_Sloc(TBMaster_Sloc instance);
    partial void UpdateTBMaster_Sloc(TBMaster_Sloc instance);
    partial void DeleteTBMaster_Sloc(TBMaster_Sloc instance);
    partial void InsertTBMaster_DHApp_Group_Detail(TBMaster_DHApp_Group_Detail instance);
    partial void UpdateTBMaster_DHApp_Group_Detail(TBMaster_DHApp_Group_Detail instance);
    partial void DeleteTBMaster_DHApp_Group_Detail(TBMaster_DHApp_Group_Detail instance);
    partial void InsertTBMaster_User(TBMaster_User instance);
    partial void UpdateTBMaster_User(TBMaster_User instance);
    partial void DeleteTBMaster_User(TBMaster_User instance);
    partial void InsertTBMaster_User_Position(TBMaster_User_Position instance);
    partial void UpdateTBMaster_User_Position(TBMaster_User_Position instance);
    partial void DeleteTBMaster_User_Position(TBMaster_User_Position instance);
    partial void InsertTBMaster_Branch(TBMaster_Branch instance);
    partial void UpdateTBMaster_Branch(TBMaster_Branch instance);
    partial void DeleteTBMaster_Branch(TBMaster_Branch instance);
    partial void InsertTBMaster_User_Job_Key(TBMaster_User_Job_Key instance);
    partial void UpdateTBMaster_User_Job_Key(TBMaster_User_Job_Key instance);
    partial void DeleteTBMaster_User_Job_Key(TBMaster_User_Job_Key instance);
    #endregion
		
		public DBMASTERDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DBMASTERConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBMASTERDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMASTERDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMASTERDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMASTERDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBMaster_DHApp_User> TBMaster_DHApp_Users
		{
			get
			{
				return this.GetTable<TBMaster_DHApp_User>();
			}
		}
		
		public System.Data.Linq.Table<TBMaster_DHApp_Group_Policy> TBMaster_DHApp_Group_Policies
		{
			get
			{
				return this.GetTable<TBMaster_DHApp_Group_Policy>();
			}
		}
		
		public System.Data.Linq.Table<TBMaster_Site> TBMaster_Sites
		{
			get
			{
				return this.GetTable<TBMaster_Site>();
			}
		}
		
		public System.Data.Linq.Table<TBMaster_Sloc> TBMaster_Slocs
		{
			get
			{
				return this.GetTable<TBMaster_Sloc>();
			}
		}
		
		public System.Data.Linq.Table<TBMaster_DHApp_Group_Detail> TBMaster_DHApp_Group_Details
		{
			get
			{
				return this.GetTable<TBMaster_DHApp_Group_Detail>();
			}
		}
		
		public System.Data.Linq.Table<TBMaster_User> TBMaster_Users
		{
			get
			{
				return this.GetTable<TBMaster_User>();
			}
		}
		
		public System.Data.Linq.Table<TBMaster_User_Position> TBMaster_User_Positions
		{
			get
			{
				return this.GetTable<TBMaster_User_Position>();
			}
		}
		
		public System.Data.Linq.Table<TBMaster_Branch> TBMaster_Branches
		{
			get
			{
				return this.GetTable<TBMaster_Branch>();
			}
		}
		
		public System.Data.Linq.Table<TBMaster_User_Job_Key> TBMaster_User_Job_Keys
		{
			get
			{
				return this.GetTable<TBMaster_User_Job_Key>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBMaster_DHApp_User")]
	public partial class TBMaster_DHApp_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _User_Code;
		
		private string _Group_Code;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_CodeChanging(string value);
    partial void OnUser_CodeChanged();
    partial void OnGroup_CodeChanging(string value);
    partial void OnGroup_CodeChanged();
    #endregion
		
		public TBMaster_DHApp_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Code", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string User_Code
		{
			get
			{
				return this._User_Code;
			}
			set
			{
				if ((this._User_Code != value))
				{
					this.OnUser_CodeChanging(value);
					this.SendPropertyChanging();
					this._User_Code = value;
					this.SendPropertyChanged("User_Code");
					this.OnUser_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Group_Code", DbType="VarChar(10)")]
		public string Group_Code
		{
			get
			{
				return this._Group_Code;
			}
			set
			{
				if ((this._Group_Code != value))
				{
					this.OnGroup_CodeChanging(value);
					this.SendPropertyChanging();
					this._Group_Code = value;
					this.SendPropertyChanged("Group_Code");
					this.OnGroup_CodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBMaster_DHApp_Group_Policy")]
	public partial class TBMaster_DHApp_Group_Policy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Group_Code;
		
		private string _Group_Name;
		
		private string _Group_Desc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGroup_CodeChanging(string value);
    partial void OnGroup_CodeChanged();
    partial void OnGroup_NameChanging(string value);
    partial void OnGroup_NameChanged();
    partial void OnGroup_DescChanging(string value);
    partial void OnGroup_DescChanged();
    #endregion
		
		public TBMaster_DHApp_Group_Policy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Group_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Group_Code
		{
			get
			{
				return this._Group_Code;
			}
			set
			{
				if ((this._Group_Code != value))
				{
					this.OnGroup_CodeChanging(value);
					this.SendPropertyChanging();
					this._Group_Code = value;
					this.SendPropertyChanged("Group_Code");
					this.OnGroup_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Group_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Group_Name
		{
			get
			{
				return this._Group_Name;
			}
			set
			{
				if ((this._Group_Name != value))
				{
					this.OnGroup_NameChanging(value);
					this.SendPropertyChanging();
					this._Group_Name = value;
					this.SendPropertyChanged("Group_Name");
					this.OnGroup_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Group_Desc", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Group_Desc
		{
			get
			{
				return this._Group_Desc;
			}
			set
			{
				if ((this._Group_Desc != value))
				{
					this.OnGroup_DescChanging(value);
					this.SendPropertyChanging();
					this._Group_Desc = value;
					this.SendPropertyChanged("Group_Desc");
					this.OnGroup_DescChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBMaster_Site")]
	public partial class TBMaster_Site : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CODE;
		
		private string _MYNAME;
		
		private System.Nullable<int> _STATUS;
		
		private System.DateTime _LAST_UPDATE_DATE;
		
		private System.DateTime _LAST_UPDATE_TIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnMYNAMEChanging(string value);
    partial void OnMYNAMEChanged();
    partial void OnSTATUSChanging(System.Nullable<int> value);
    partial void OnSTATUSChanged();
    partial void OnLAST_UPDATE_DATEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_DATEChanged();
    partial void OnLAST_UPDATE_TIMEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_TIMEChanged();
    #endregion
		
		public TBMaster_Site()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MYNAME", DbType="VarChar(100)")]
		public string MYNAME
		{
			get
			{
				return this._MYNAME;
			}
			set
			{
				if ((this._MYNAME != value))
				{
					this.OnMYNAMEChanging(value);
					this.SendPropertyChanging();
					this._MYNAME = value;
					this.SendPropertyChanged("MYNAME");
					this.OnMYNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_DATE
		{
			get
			{
				return this._LAST_UPDATE_DATE;
			}
			set
			{
				if ((this._LAST_UPDATE_DATE != value))
				{
					this.OnLAST_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_DATE = value;
					this.SendPropertyChanged("LAST_UPDATE_DATE");
					this.OnLAST_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_TIME
		{
			get
			{
				return this._LAST_UPDATE_TIME;
			}
			set
			{
				if ((this._LAST_UPDATE_TIME != value))
				{
					this.OnLAST_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_TIME = value;
					this.SendPropertyChanged("LAST_UPDATE_TIME");
					this.OnLAST_UPDATE_TIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBMaster_Sloc")]
	public partial class TBMaster_Sloc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SITECODE;
		
		private string _SLOC;
		
		private string _SLOC_NAME;
		
		private System.DateTime _LAST_UPDATE_DATE;
		
		private System.DateTime _LAST_UPDATE_TIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSITECODEChanging(string value);
    partial void OnSITECODEChanged();
    partial void OnSLOCChanging(string value);
    partial void OnSLOCChanged();
    partial void OnSLOC_NAMEChanging(string value);
    partial void OnSLOC_NAMEChanged();
    partial void OnLAST_UPDATE_DATEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_DATEChanged();
    partial void OnLAST_UPDATE_TIMEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_TIMEChanged();
    #endregion
		
		public TBMaster_Sloc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITECODE", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SITECODE
		{
			get
			{
				return this._SITECODE;
			}
			set
			{
				if ((this._SITECODE != value))
				{
					this.OnSITECODEChanging(value);
					this.SendPropertyChanging();
					this._SITECODE = value;
					this.SendPropertyChanged("SITECODE");
					this.OnSITECODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLOC", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SLOC
		{
			get
			{
				return this._SLOC;
			}
			set
			{
				if ((this._SLOC != value))
				{
					this.OnSLOCChanging(value);
					this.SendPropertyChanging();
					this._SLOC = value;
					this.SendPropertyChanged("SLOC");
					this.OnSLOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLOC_NAME", DbType="VarChar(150)")]
		public string SLOC_NAME
		{
			get
			{
				return this._SLOC_NAME;
			}
			set
			{
				if ((this._SLOC_NAME != value))
				{
					this.OnSLOC_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SLOC_NAME = value;
					this.SendPropertyChanged("SLOC_NAME");
					this.OnSLOC_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_DATE
		{
			get
			{
				return this._LAST_UPDATE_DATE;
			}
			set
			{
				if ((this._LAST_UPDATE_DATE != value))
				{
					this.OnLAST_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_DATE = value;
					this.SendPropertyChanged("LAST_UPDATE_DATE");
					this.OnLAST_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_TIME
		{
			get
			{
				return this._LAST_UPDATE_TIME;
			}
			set
			{
				if ((this._LAST_UPDATE_TIME != value))
				{
					this.OnLAST_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_TIME = value;
					this.SendPropertyChanged("LAST_UPDATE_TIME");
					this.OnLAST_UPDATE_TIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBMaster_DHApp_Group_Detail")]
	public partial class TBMaster_DHApp_Group_Detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Site;
		
		private string _Sloc;
		
		private string _Group_Code;
		
		private string _Branch;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSiteChanging(string value);
    partial void OnSiteChanged();
    partial void OnSlocChanging(string value);
    partial void OnSlocChanged();
    partial void OnGroup_CodeChanging(string value);
    partial void OnGroup_CodeChanged();
    partial void OnBranchChanging(string value);
    partial void OnBranchChanged();
    #endregion
		
		public TBMaster_DHApp_Group_Detail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Site
		{
			get
			{
				return this._Site;
			}
			set
			{
				if ((this._Site != value))
				{
					this.OnSiteChanging(value);
					this.SendPropertyChanging();
					this._Site = value;
					this.SendPropertyChanged("Site");
					this.OnSiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sloc", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Sloc
		{
			get
			{
				return this._Sloc;
			}
			set
			{
				if ((this._Sloc != value))
				{
					this.OnSlocChanging(value);
					this.SendPropertyChanging();
					this._Sloc = value;
					this.SendPropertyChanged("Sloc");
					this.OnSlocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Group_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Group_Code
		{
			get
			{
				return this._Group_Code;
			}
			set
			{
				if ((this._Group_Code != value))
				{
					this.OnGroup_CodeChanging(value);
					this.SendPropertyChanging();
					this._Group_Code = value;
					this.SendPropertyChanged("Group_Code");
					this.OnGroup_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Branch
		{
			get
			{
				return this._Branch;
			}
			set
			{
				if ((this._Branch != value))
				{
					this.OnBranchChanging(value);
					this.SendPropertyChanging();
					this._Branch = value;
					this.SendPropertyChanged("Branch");
					this.OnBranchChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBMaster_User")]
	public partial class TBMaster_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CODE;
		
		private string _MYNAME;
		
		private string _FIRST_NAME;
		
		private string _LAST_NAME;
		
		private string _JOBKEY;
		
		private string _POSITION;
		
		private System.Nullable<System.DateTime> _BEGINDATE;
		
		private System.Nullable<System.DateTime> _ENDDATE;
		
		private string _WERKS;
		
		private System.Nullable<int> _STATUS;
		
		private System.DateTime _LAST_UPDATE_DATE;
		
		private System.DateTime _LAST_UPDATE_TIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnMYNAMEChanging(string value);
    partial void OnMYNAMEChanged();
    partial void OnFIRST_NAMEChanging(string value);
    partial void OnFIRST_NAMEChanged();
    partial void OnLAST_NAMEChanging(string value);
    partial void OnLAST_NAMEChanged();
    partial void OnJOBKEYChanging(string value);
    partial void OnJOBKEYChanged();
    partial void OnPOSITIONChanging(string value);
    partial void OnPOSITIONChanged();
    partial void OnBEGINDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnBEGINDATEChanged();
    partial void OnENDDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnENDDATEChanged();
    partial void OnWERKSChanging(string value);
    partial void OnWERKSChanged();
    partial void OnSTATUSChanging(System.Nullable<int> value);
    partial void OnSTATUSChanged();
    partial void OnLAST_UPDATE_DATEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_DATEChanged();
    partial void OnLAST_UPDATE_TIMEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_TIMEChanged();
    #endregion
		
		public TBMaster_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MYNAME", DbType="VarChar(250)")]
		public string MYNAME
		{
			get
			{
				return this._MYNAME;
			}
			set
			{
				if ((this._MYNAME != value))
				{
					this.OnMYNAMEChanging(value);
					this.SendPropertyChanging();
					this._MYNAME = value;
					this.SendPropertyChanged("MYNAME");
					this.OnMYNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRST_NAME", DbType="VarChar(50)")]
		public string FIRST_NAME
		{
			get
			{
				return this._FIRST_NAME;
			}
			set
			{
				if ((this._FIRST_NAME != value))
				{
					this.OnFIRST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FIRST_NAME = value;
					this.SendPropertyChanged("FIRST_NAME");
					this.OnFIRST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_NAME", DbType="VarChar(50)")]
		public string LAST_NAME
		{
			get
			{
				return this._LAST_NAME;
			}
			set
			{
				if ((this._LAST_NAME != value))
				{
					this.OnLAST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_NAME = value;
					this.SendPropertyChanged("LAST_NAME");
					this.OnLAST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOBKEY", DbType="VarChar(50)")]
		public string JOBKEY
		{
			get
			{
				return this._JOBKEY;
			}
			set
			{
				if ((this._JOBKEY != value))
				{
					this.OnJOBKEYChanging(value);
					this.SendPropertyChanging();
					this._JOBKEY = value;
					this.SendPropertyChanged("JOBKEY");
					this.OnJOBKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION", DbType="VarChar(50)")]
		public string POSITION
		{
			get
			{
				return this._POSITION;
			}
			set
			{
				if ((this._POSITION != value))
				{
					this.OnPOSITIONChanging(value);
					this.SendPropertyChanging();
					this._POSITION = value;
					this.SendPropertyChanged("POSITION");
					this.OnPOSITIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BEGINDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> BEGINDATE
		{
			get
			{
				return this._BEGINDATE;
			}
			set
			{
				if ((this._BEGINDATE != value))
				{
					this.OnBEGINDATEChanging(value);
					this.SendPropertyChanging();
					this._BEGINDATE = value;
					this.SendPropertyChanged("BEGINDATE");
					this.OnBEGINDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> ENDDATE
		{
			get
			{
				return this._ENDDATE;
			}
			set
			{
				if ((this._ENDDATE != value))
				{
					this.OnENDDATEChanging(value);
					this.SendPropertyChanging();
					this._ENDDATE = value;
					this.SendPropertyChanged("ENDDATE");
					this.OnENDDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WERKS", DbType="VarChar(50)")]
		public string WERKS
		{
			get
			{
				return this._WERKS;
			}
			set
			{
				if ((this._WERKS != value))
				{
					this.OnWERKSChanging(value);
					this.SendPropertyChanging();
					this._WERKS = value;
					this.SendPropertyChanged("WERKS");
					this.OnWERKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_DATE
		{
			get
			{
				return this._LAST_UPDATE_DATE;
			}
			set
			{
				if ((this._LAST_UPDATE_DATE != value))
				{
					this.OnLAST_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_DATE = value;
					this.SendPropertyChanged("LAST_UPDATE_DATE");
					this.OnLAST_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_TIME
		{
			get
			{
				return this._LAST_UPDATE_TIME;
			}
			set
			{
				if ((this._LAST_UPDATE_TIME != value))
				{
					this.OnLAST_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_TIME = value;
					this.SendPropertyChanged("LAST_UPDATE_TIME");
					this.OnLAST_UPDATE_TIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBMaster_User_Position")]
	public partial class TBMaster_User_Position : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CODE;
		
		private string _MYNAME;
		
		private System.DateTime _LAST_UPDATE_DATE;
		
		private System.DateTime _LAST_UPDATE_TIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnMYNAMEChanging(string value);
    partial void OnMYNAMEChanged();
    partial void OnLAST_UPDATE_DATEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_DATEChanged();
    partial void OnLAST_UPDATE_TIMEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_TIMEChanged();
    #endregion
		
		public TBMaster_User_Position()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MYNAME", DbType="VarChar(150)")]
		public string MYNAME
		{
			get
			{
				return this._MYNAME;
			}
			set
			{
				if ((this._MYNAME != value))
				{
					this.OnMYNAMEChanging(value);
					this.SendPropertyChanging();
					this._MYNAME = value;
					this.SendPropertyChanged("MYNAME");
					this.OnMYNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_DATE
		{
			get
			{
				return this._LAST_UPDATE_DATE;
			}
			set
			{
				if ((this._LAST_UPDATE_DATE != value))
				{
					this.OnLAST_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_DATE = value;
					this.SendPropertyChanged("LAST_UPDATE_DATE");
					this.OnLAST_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_TIME
		{
			get
			{
				return this._LAST_UPDATE_TIME;
			}
			set
			{
				if ((this._LAST_UPDATE_TIME != value))
				{
					this.OnLAST_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_TIME = value;
					this.SendPropertyChanged("LAST_UPDATE_TIME");
					this.OnLAST_UPDATE_TIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBMaster_Branch")]
	public partial class TBMaster_Branch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CODE;
		
		private string _OLD_CODE;
		
		private string _MYNAME;
		
		private int _STATUS;
		
		private string _ADDRESS;
		
		private string _TEL;
		
		private string _FAX;
		
		private string _HOTLINE;
		
		private string _TAXID;
		
		private string _BRANCHCODE;
		
		private string _SHORT_NAME;
		
		private string _SERVER_NAME;
		
		private string _SERVER_IP;
		
		private string _DB_MASTER_NAME;
		
		private string _DB_TRANS_NAME;
		
		private System.DateTime _LAST_UPDATE_DATE;
		
		private System.DateTime _LAST_UPDATE_TIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnOLD_CODEChanging(string value);
    partial void OnOLD_CODEChanged();
    partial void OnMYNAMEChanging(string value);
    partial void OnMYNAMEChanged();
    partial void OnSTATUSChanging(int value);
    partial void OnSTATUSChanged();
    partial void OnADDRESSChanging(string value);
    partial void OnADDRESSChanged();
    partial void OnTELChanging(string value);
    partial void OnTELChanged();
    partial void OnFAXChanging(string value);
    partial void OnFAXChanged();
    partial void OnHOTLINEChanging(string value);
    partial void OnHOTLINEChanged();
    partial void OnTAXIDChanging(string value);
    partial void OnTAXIDChanged();
    partial void OnBRANCHCODEChanging(string value);
    partial void OnBRANCHCODEChanged();
    partial void OnSHORT_NAMEChanging(string value);
    partial void OnSHORT_NAMEChanged();
    partial void OnSERVER_NAMEChanging(string value);
    partial void OnSERVER_NAMEChanged();
    partial void OnSERVER_IPChanging(string value);
    partial void OnSERVER_IPChanged();
    partial void OnDB_MASTER_NAMEChanging(string value);
    partial void OnDB_MASTER_NAMEChanged();
    partial void OnDB_TRANS_NAMEChanging(string value);
    partial void OnDB_TRANS_NAMEChanged();
    partial void OnLAST_UPDATE_DATEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_DATEChanged();
    partial void OnLAST_UPDATE_TIMEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_TIMEChanged();
    #endregion
		
		public TBMaster_Branch()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OLD_CODE", DbType="VarChar(50)")]
		public string OLD_CODE
		{
			get
			{
				return this._OLD_CODE;
			}
			set
			{
				if ((this._OLD_CODE != value))
				{
					this.OnOLD_CODEChanging(value);
					this.SendPropertyChanging();
					this._OLD_CODE = value;
					this.SendPropertyChanged("OLD_CODE");
					this.OnOLD_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MYNAME", DbType="VarChar(150)")]
		public string MYNAME
		{
			get
			{
				return this._MYNAME;
			}
			set
			{
				if ((this._MYNAME != value))
				{
					this.OnMYNAMEChanging(value);
					this.SendPropertyChanging();
					this._MYNAME = value;
					this.SendPropertyChanged("MYNAME");
					this.OnMYNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int NOT NULL")]
		public int STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="VarChar(200)")]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this.OnADDRESSChanging(value);
					this.SendPropertyChanging();
					this._ADDRESS = value;
					this.SendPropertyChanged("ADDRESS");
					this.OnADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEL", DbType="VarChar(50)")]
		public string TEL
		{
			get
			{
				return this._TEL;
			}
			set
			{
				if ((this._TEL != value))
				{
					this.OnTELChanging(value);
					this.SendPropertyChanging();
					this._TEL = value;
					this.SendPropertyChanged("TEL");
					this.OnTELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX", DbType="VarChar(50)")]
		public string FAX
		{
			get
			{
				return this._FAX;
			}
			set
			{
				if ((this._FAX != value))
				{
					this.OnFAXChanging(value);
					this.SendPropertyChanging();
					this._FAX = value;
					this.SendPropertyChanged("FAX");
					this.OnFAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTLINE", DbType="VarChar(50)")]
		public string HOTLINE
		{
			get
			{
				return this._HOTLINE;
			}
			set
			{
				if ((this._HOTLINE != value))
				{
					this.OnHOTLINEChanging(value);
					this.SendPropertyChanging();
					this._HOTLINE = value;
					this.SendPropertyChanged("HOTLINE");
					this.OnHOTLINEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAXID", DbType="VarChar(50)")]
		public string TAXID
		{
			get
			{
				return this._TAXID;
			}
			set
			{
				if ((this._TAXID != value))
				{
					this.OnTAXIDChanging(value);
					this.SendPropertyChanging();
					this._TAXID = value;
					this.SendPropertyChanged("TAXID");
					this.OnTAXIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCHCODE", DbType="VarChar(50)")]
		public string BRANCHCODE
		{
			get
			{
				return this._BRANCHCODE;
			}
			set
			{
				if ((this._BRANCHCODE != value))
				{
					this.OnBRANCHCODEChanging(value);
					this.SendPropertyChanging();
					this._BRANCHCODE = value;
					this.SendPropertyChanged("BRANCHCODE");
					this.OnBRANCHCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHORT_NAME", DbType="VarChar(50)")]
		public string SHORT_NAME
		{
			get
			{
				return this._SHORT_NAME;
			}
			set
			{
				if ((this._SHORT_NAME != value))
				{
					this.OnSHORT_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SHORT_NAME = value;
					this.SendPropertyChanged("SHORT_NAME");
					this.OnSHORT_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVER_NAME", DbType="VarChar(50)")]
		public string SERVER_NAME
		{
			get
			{
				return this._SERVER_NAME;
			}
			set
			{
				if ((this._SERVER_NAME != value))
				{
					this.OnSERVER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SERVER_NAME = value;
					this.SendPropertyChanged("SERVER_NAME");
					this.OnSERVER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVER_IP", DbType="VarChar(50)")]
		public string SERVER_IP
		{
			get
			{
				return this._SERVER_IP;
			}
			set
			{
				if ((this._SERVER_IP != value))
				{
					this.OnSERVER_IPChanging(value);
					this.SendPropertyChanging();
					this._SERVER_IP = value;
					this.SendPropertyChanged("SERVER_IP");
					this.OnSERVER_IPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB_MASTER_NAME", DbType="VarChar(50)")]
		public string DB_MASTER_NAME
		{
			get
			{
				return this._DB_MASTER_NAME;
			}
			set
			{
				if ((this._DB_MASTER_NAME != value))
				{
					this.OnDB_MASTER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DB_MASTER_NAME = value;
					this.SendPropertyChanged("DB_MASTER_NAME");
					this.OnDB_MASTER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB_TRANS_NAME", DbType="VarChar(50)")]
		public string DB_TRANS_NAME
		{
			get
			{
				return this._DB_TRANS_NAME;
			}
			set
			{
				if ((this._DB_TRANS_NAME != value))
				{
					this.OnDB_TRANS_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DB_TRANS_NAME = value;
					this.SendPropertyChanged("DB_TRANS_NAME");
					this.OnDB_TRANS_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_DATE
		{
			get
			{
				return this._LAST_UPDATE_DATE;
			}
			set
			{
				if ((this._LAST_UPDATE_DATE != value))
				{
					this.OnLAST_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_DATE = value;
					this.SendPropertyChanged("LAST_UPDATE_DATE");
					this.OnLAST_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_TIME
		{
			get
			{
				return this._LAST_UPDATE_TIME;
			}
			set
			{
				if ((this._LAST_UPDATE_TIME != value))
				{
					this.OnLAST_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_TIME = value;
					this.SendPropertyChanged("LAST_UPDATE_TIME");
					this.OnLAST_UPDATE_TIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBMaster_User_Job_Key")]
	public partial class TBMaster_User_Job_Key : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CODE;
		
		private string _MYNAME;
		
		private string _JOBKEYTYPE;
		
		private System.DateTime _LAST_UPDATE_DATE;
		
		private System.DateTime _LAST_UPDATE_TIME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnMYNAMEChanging(string value);
    partial void OnMYNAMEChanged();
    partial void OnJOBKEYTYPEChanging(string value);
    partial void OnJOBKEYTYPEChanged();
    partial void OnLAST_UPDATE_DATEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_DATEChanged();
    partial void OnLAST_UPDATE_TIMEChanging(System.DateTime value);
    partial void OnLAST_UPDATE_TIMEChanged();
    #endregion
		
		public TBMaster_User_Job_Key()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MYNAME", DbType="VarChar(150)")]
		public string MYNAME
		{
			get
			{
				return this._MYNAME;
			}
			set
			{
				if ((this._MYNAME != value))
				{
					this.OnMYNAMEChanging(value);
					this.SendPropertyChanging();
					this._MYNAME = value;
					this.SendPropertyChanged("MYNAME");
					this.OnMYNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOBKEYTYPE", DbType="VarChar(50)")]
		public string JOBKEYTYPE
		{
			get
			{
				return this._JOBKEYTYPE;
			}
			set
			{
				if ((this._JOBKEYTYPE != value))
				{
					this.OnJOBKEYTYPEChanging(value);
					this.SendPropertyChanging();
					this._JOBKEYTYPE = value;
					this.SendPropertyChanged("JOBKEYTYPE");
					this.OnJOBKEYTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_DATE
		{
			get
			{
				return this._LAST_UPDATE_DATE;
			}
			set
			{
				if ((this._LAST_UPDATE_DATE != value))
				{
					this.OnLAST_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_DATE = value;
					this.SendPropertyChanged("LAST_UPDATE_DATE");
					this.OnLAST_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime LAST_UPDATE_TIME
		{
			get
			{
				return this._LAST_UPDATE_TIME;
			}
			set
			{
				if ((this._LAST_UPDATE_TIME != value))
				{
					this.OnLAST_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_TIME = value;
					this.SendPropertyChanged("LAST_UPDATE_TIME");
					this.OnLAST_UPDATE_TIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
