//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TMSWebService.DO_WebReferencePRD {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DHMServiceSoap", Namespace="http://www.onelink.co.th/DHMService")]
    public partial class DHMService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback OTSReceiveShipToOperationCompleted;
        
        private System.Threading.SendOrPostCallback OTSReceiveShipToFromSAPOperationCompleted;
        
        private System.Threading.SendOrPostCallback OTSReciveQDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback OTSReciveValueFuelOperationCompleted;
        
        private System.Threading.SendOrPostCallback OTSReciveRealFuelOperationCompleted;
        
        private System.Threading.SendOrPostCallback OTSReciveCostPerDistanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback OTSCheckPlanStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback OTSReciveQDriverOperationCompleted;
        
        private System.Threading.SendOrPostCallback OTSCancelQDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback OTSReqCustomDistanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback OTSReqShipToDistanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback OTSPlanningOperationCompleted;
        
        private System.Threading.SendOrPostCallback OTSAdjustPlanningOperationCompleted;
        
        private System.Threading.SendOrPostCallback OTSAssignVehicleOperationCompleted;
        
        private System.Threading.SendOrPostCallback OTSCancelPlanOperationCompleted;
        
        private System.Threading.SendOrPostCallback OTSUpdClosePlanOperationCompleted;
        
        private System.Threading.SendOrPostCallback OTSRecvDebtInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback OTSRecvCashInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback OTSCheckDOExistsOperationCompleted;
        
        private System.Threading.SendOrPostCallback OTSCheckShipToFileExistsOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestOTSShipToOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestOTSDOOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestPlanningOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestOTSRecvDebtInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestOTSRecvCashInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestAdjustRouteOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestShipToRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestAssignVehicleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DHMService() {
            this.Url = global::TMSWebService.Properties.Settings.Default.TMSWebService_DO_WebReferencePRD_DHMService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event OTSReceiveShipToCompletedEventHandler OTSReceiveShipToCompleted;
        
        /// <remarks/>
        public event OTSReceiveShipToFromSAPCompletedEventHandler OTSReceiveShipToFromSAPCompleted;
        
        /// <remarks/>
        public event OTSReciveQDataCompletedEventHandler OTSReciveQDataCompleted;
        
        /// <remarks/>
        public event OTSReciveValueFuelCompletedEventHandler OTSReciveValueFuelCompleted;
        
        /// <remarks/>
        public event OTSReciveRealFuelCompletedEventHandler OTSReciveRealFuelCompleted;
        
        /// <remarks/>
        public event OTSReciveCostPerDistanceCompletedEventHandler OTSReciveCostPerDistanceCompleted;
        
        /// <remarks/>
        public event OTSCheckPlanStatusCompletedEventHandler OTSCheckPlanStatusCompleted;
        
        /// <remarks/>
        public event OTSReciveQDriverCompletedEventHandler OTSReciveQDriverCompleted;
        
        /// <remarks/>
        public event OTSCancelQDataCompletedEventHandler OTSCancelQDataCompleted;
        
        /// <remarks/>
        public event OTSReqCustomDistanceCompletedEventHandler OTSReqCustomDistanceCompleted;
        
        /// <remarks/>
        public event OTSReqShipToDistanceCompletedEventHandler OTSReqShipToDistanceCompleted;
        
        /// <remarks/>
        public event OTSPlanningCompletedEventHandler OTSPlanningCompleted;
        
        /// <remarks/>
        public event OTSAdjustPlanningCompletedEventHandler OTSAdjustPlanningCompleted;
        
        /// <remarks/>
        public event OTSAssignVehicleCompletedEventHandler OTSAssignVehicleCompleted;
        
        /// <remarks/>
        public event OTSCancelPlanCompletedEventHandler OTSCancelPlanCompleted;
        
        /// <remarks/>
        public event OTSUpdClosePlanCompletedEventHandler OTSUpdClosePlanCompleted;
        
        /// <remarks/>
        public event OTSRecvDebtInfoCompletedEventHandler OTSRecvDebtInfoCompleted;
        
        /// <remarks/>
        public event OTSRecvCashInfoCompletedEventHandler OTSRecvCashInfoCompleted;
        
        /// <remarks/>
        public event OTSCheckDOExistsCompletedEventHandler OTSCheckDOExistsCompleted;
        
        /// <remarks/>
        public event OTSCheckShipToFileExistsCompletedEventHandler OTSCheckShipToFileExistsCompleted;
        
        /// <remarks/>
        public event TestOTSShipToCompletedEventHandler TestOTSShipToCompleted;
        
        /// <remarks/>
        public event TestOTSDOCompletedEventHandler TestOTSDOCompleted;
        
        /// <remarks/>
        public event TestPlanningCompletedEventHandler TestPlanningCompleted;
        
        /// <remarks/>
        public event TestOTSRecvDebtInfoCompletedEventHandler TestOTSRecvDebtInfoCompleted;
        
        /// <remarks/>
        public event TestOTSRecvCashInfoCompletedEventHandler TestOTSRecvCashInfoCompleted;
        
        /// <remarks/>
        public event TestAdjustRouteCompletedEventHandler TestAdjustRouteCompleted;
        
        /// <remarks/>
        public event TestShipToRequestCompletedEventHandler TestShipToRequestCompleted;
        
        /// <remarks/>
        public event TestAssignVehicleCompletedEventHandler TestAssignVehicleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/OTSReceiveShipTo", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OTSReceiveShipTo(string strXML) {
            object[] results = this.Invoke("OTSReceiveShipTo", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OTSReceiveShipToAsync(string strXML) {
            this.OTSReceiveShipToAsync(strXML, null);
        }
        
        /// <remarks/>
        public void OTSReceiveShipToAsync(string strXML, object userState) {
            if ((this.OTSReceiveShipToOperationCompleted == null)) {
                this.OTSReceiveShipToOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOTSReceiveShipToOperationCompleted);
            }
            this.InvokeAsync("OTSReceiveShipTo", new object[] {
                        strXML}, this.OTSReceiveShipToOperationCompleted, userState);
        }
        
        private void OnOTSReceiveShipToOperationCompleted(object arg) {
            if ((this.OTSReceiveShipToCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OTSReceiveShipToCompleted(this, new OTSReceiveShipToCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/OTSReceiveShipToFromSAP", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OTSReceiveShipToFromSAP(string strXML) {
            object[] results = this.Invoke("OTSReceiveShipToFromSAP", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OTSReceiveShipToFromSAPAsync(string strXML) {
            this.OTSReceiveShipToFromSAPAsync(strXML, null);
        }
        
        /// <remarks/>
        public void OTSReceiveShipToFromSAPAsync(string strXML, object userState) {
            if ((this.OTSReceiveShipToFromSAPOperationCompleted == null)) {
                this.OTSReceiveShipToFromSAPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOTSReceiveShipToFromSAPOperationCompleted);
            }
            this.InvokeAsync("OTSReceiveShipToFromSAP", new object[] {
                        strXML}, this.OTSReceiveShipToFromSAPOperationCompleted, userState);
        }
        
        private void OnOTSReceiveShipToFromSAPOperationCompleted(object arg) {
            if ((this.OTSReceiveShipToFromSAPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OTSReceiveShipToFromSAPCompleted(this, new OTSReceiveShipToFromSAPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/OTSReciveQData", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OTSReciveQData(string strXML) {
            object[] results = this.Invoke("OTSReciveQData", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OTSReciveQDataAsync(string strXML) {
            this.OTSReciveQDataAsync(strXML, null);
        }
        
        /// <remarks/>
        public void OTSReciveQDataAsync(string strXML, object userState) {
            if ((this.OTSReciveQDataOperationCompleted == null)) {
                this.OTSReciveQDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOTSReciveQDataOperationCompleted);
            }
            this.InvokeAsync("OTSReciveQData", new object[] {
                        strXML}, this.OTSReciveQDataOperationCompleted, userState);
        }
        
        private void OnOTSReciveQDataOperationCompleted(object arg) {
            if ((this.OTSReciveQDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OTSReciveQDataCompleted(this, new OTSReciveQDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/OTSReciveValueFuel", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OTSReciveValueFuel(string strXML) {
            object[] results = this.Invoke("OTSReciveValueFuel", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OTSReciveValueFuelAsync(string strXML) {
            this.OTSReciveValueFuelAsync(strXML, null);
        }
        
        /// <remarks/>
        public void OTSReciveValueFuelAsync(string strXML, object userState) {
            if ((this.OTSReciveValueFuelOperationCompleted == null)) {
                this.OTSReciveValueFuelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOTSReciveValueFuelOperationCompleted);
            }
            this.InvokeAsync("OTSReciveValueFuel", new object[] {
                        strXML}, this.OTSReciveValueFuelOperationCompleted, userState);
        }
        
        private void OnOTSReciveValueFuelOperationCompleted(object arg) {
            if ((this.OTSReciveValueFuelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OTSReciveValueFuelCompleted(this, new OTSReciveValueFuelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/OTSReciveRealFuel", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OTSReciveRealFuel(string strXML) {
            object[] results = this.Invoke("OTSReciveRealFuel", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OTSReciveRealFuelAsync(string strXML) {
            this.OTSReciveRealFuelAsync(strXML, null);
        }
        
        /// <remarks/>
        public void OTSReciveRealFuelAsync(string strXML, object userState) {
            if ((this.OTSReciveRealFuelOperationCompleted == null)) {
                this.OTSReciveRealFuelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOTSReciveRealFuelOperationCompleted);
            }
            this.InvokeAsync("OTSReciveRealFuel", new object[] {
                        strXML}, this.OTSReciveRealFuelOperationCompleted, userState);
        }
        
        private void OnOTSReciveRealFuelOperationCompleted(object arg) {
            if ((this.OTSReciveRealFuelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OTSReciveRealFuelCompleted(this, new OTSReciveRealFuelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/OTSReciveCostPerDistance", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OTSReciveCostPerDistance(string strXML) {
            object[] results = this.Invoke("OTSReciveCostPerDistance", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OTSReciveCostPerDistanceAsync(string strXML) {
            this.OTSReciveCostPerDistanceAsync(strXML, null);
        }
        
        /// <remarks/>
        public void OTSReciveCostPerDistanceAsync(string strXML, object userState) {
            if ((this.OTSReciveCostPerDistanceOperationCompleted == null)) {
                this.OTSReciveCostPerDistanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOTSReciveCostPerDistanceOperationCompleted);
            }
            this.InvokeAsync("OTSReciveCostPerDistance", new object[] {
                        strXML}, this.OTSReciveCostPerDistanceOperationCompleted, userState);
        }
        
        private void OnOTSReciveCostPerDistanceOperationCompleted(object arg) {
            if ((this.OTSReciveCostPerDistanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OTSReciveCostPerDistanceCompleted(this, new OTSReciveCostPerDistanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/OTSCheckPlanStatus", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OTSCheckPlanStatus(string SapPlanId) {
            object[] results = this.Invoke("OTSCheckPlanStatus", new object[] {
                        SapPlanId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OTSCheckPlanStatusAsync(string SapPlanId) {
            this.OTSCheckPlanStatusAsync(SapPlanId, null);
        }
        
        /// <remarks/>
        public void OTSCheckPlanStatusAsync(string SapPlanId, object userState) {
            if ((this.OTSCheckPlanStatusOperationCompleted == null)) {
                this.OTSCheckPlanStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOTSCheckPlanStatusOperationCompleted);
            }
            this.InvokeAsync("OTSCheckPlanStatus", new object[] {
                        SapPlanId}, this.OTSCheckPlanStatusOperationCompleted, userState);
        }
        
        private void OnOTSCheckPlanStatusOperationCompleted(object arg) {
            if ((this.OTSCheckPlanStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OTSCheckPlanStatusCompleted(this, new OTSCheckPlanStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/OTSReciveQDriver", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OTSReciveQDriver(System.Data.DataSet ds) {
            object[] results = this.Invoke("OTSReciveQDriver", new object[] {
                        ds});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OTSReciveQDriverAsync(System.Data.DataSet ds) {
            this.OTSReciveQDriverAsync(ds, null);
        }
        
        /// <remarks/>
        public void OTSReciveQDriverAsync(System.Data.DataSet ds, object userState) {
            if ((this.OTSReciveQDriverOperationCompleted == null)) {
                this.OTSReciveQDriverOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOTSReciveQDriverOperationCompleted);
            }
            this.InvokeAsync("OTSReciveQDriver", new object[] {
                        ds}, this.OTSReciveQDriverOperationCompleted, userState);
        }
        
        private void OnOTSReciveQDriverOperationCompleted(object arg) {
            if ((this.OTSReciveQDriverCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OTSReciveQDriverCompleted(this, new OTSReciveQDriverCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/OTSCancelQData", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OTSCancelQData(string strXML) {
            object[] results = this.Invoke("OTSCancelQData", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OTSCancelQDataAsync(string strXML) {
            this.OTSCancelQDataAsync(strXML, null);
        }
        
        /// <remarks/>
        public void OTSCancelQDataAsync(string strXML, object userState) {
            if ((this.OTSCancelQDataOperationCompleted == null)) {
                this.OTSCancelQDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOTSCancelQDataOperationCompleted);
            }
            this.InvokeAsync("OTSCancelQData", new object[] {
                        strXML}, this.OTSCancelQDataOperationCompleted, userState);
        }
        
        private void OnOTSCancelQDataOperationCompleted(object arg) {
            if ((this.OTSCancelQDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OTSCancelQDataCompleted(this, new OTSCancelQDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/OTSReqCustomDistance", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OTSReqCustomDistance(string strXML) {
            object[] results = this.Invoke("OTSReqCustomDistance", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OTSReqCustomDistanceAsync(string strXML) {
            this.OTSReqCustomDistanceAsync(strXML, null);
        }
        
        /// <remarks/>
        public void OTSReqCustomDistanceAsync(string strXML, object userState) {
            if ((this.OTSReqCustomDistanceOperationCompleted == null)) {
                this.OTSReqCustomDistanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOTSReqCustomDistanceOperationCompleted);
            }
            this.InvokeAsync("OTSReqCustomDistance", new object[] {
                        strXML}, this.OTSReqCustomDistanceOperationCompleted, userState);
        }
        
        private void OnOTSReqCustomDistanceOperationCompleted(object arg) {
            if ((this.OTSReqCustomDistanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OTSReqCustomDistanceCompleted(this, new OTSReqCustomDistanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/OTSReqShipToDistance", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OTSReqShipToDistance(string strXML) {
            object[] results = this.Invoke("OTSReqShipToDistance", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OTSReqShipToDistanceAsync(string strXML) {
            this.OTSReqShipToDistanceAsync(strXML, null);
        }
        
        /// <remarks/>
        public void OTSReqShipToDistanceAsync(string strXML, object userState) {
            if ((this.OTSReqShipToDistanceOperationCompleted == null)) {
                this.OTSReqShipToDistanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOTSReqShipToDistanceOperationCompleted);
            }
            this.InvokeAsync("OTSReqShipToDistance", new object[] {
                        strXML}, this.OTSReqShipToDistanceOperationCompleted, userState);
        }
        
        private void OnOTSReqShipToDistanceOperationCompleted(object arg) {
            if ((this.OTSReqShipToDistanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OTSReqShipToDistanceCompleted(this, new OTSReqShipToDistanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/OTSPlanning", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OTSPlanning(string strXML) {
            object[] results = this.Invoke("OTSPlanning", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OTSPlanningAsync(string strXML) {
            this.OTSPlanningAsync(strXML, null);
        }
        
        /// <remarks/>
        public void OTSPlanningAsync(string strXML, object userState) {
            if ((this.OTSPlanningOperationCompleted == null)) {
                this.OTSPlanningOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOTSPlanningOperationCompleted);
            }
            this.InvokeAsync("OTSPlanning", new object[] {
                        strXML}, this.OTSPlanningOperationCompleted, userState);
        }
        
        private void OnOTSPlanningOperationCompleted(object arg) {
            if ((this.OTSPlanningCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OTSPlanningCompleted(this, new OTSPlanningCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/OTSAdjustPlanning", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OTSAdjustPlanning(string strXML) {
            object[] results = this.Invoke("OTSAdjustPlanning", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OTSAdjustPlanningAsync(string strXML) {
            this.OTSAdjustPlanningAsync(strXML, null);
        }
        
        /// <remarks/>
        public void OTSAdjustPlanningAsync(string strXML, object userState) {
            if ((this.OTSAdjustPlanningOperationCompleted == null)) {
                this.OTSAdjustPlanningOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOTSAdjustPlanningOperationCompleted);
            }
            this.InvokeAsync("OTSAdjustPlanning", new object[] {
                        strXML}, this.OTSAdjustPlanningOperationCompleted, userState);
        }
        
        private void OnOTSAdjustPlanningOperationCompleted(object arg) {
            if ((this.OTSAdjustPlanningCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OTSAdjustPlanningCompleted(this, new OTSAdjustPlanningCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/OTSAssignVehicle", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OTSAssignVehicle(string strXML) {
            object[] results = this.Invoke("OTSAssignVehicle", new object[] {
                        strXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OTSAssignVehicleAsync(string strXML) {
            this.OTSAssignVehicleAsync(strXML, null);
        }
        
        /// <remarks/>
        public void OTSAssignVehicleAsync(string strXML, object userState) {
            if ((this.OTSAssignVehicleOperationCompleted == null)) {
                this.OTSAssignVehicleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOTSAssignVehicleOperationCompleted);
            }
            this.InvokeAsync("OTSAssignVehicle", new object[] {
                        strXML}, this.OTSAssignVehicleOperationCompleted, userState);
        }
        
        private void OnOTSAssignVehicleOperationCompleted(object arg) {
            if ((this.OTSAssignVehicleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OTSAssignVehicleCompleted(this, new OTSAssignVehicleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/OTSCancelPlan", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OTSCancelPlan(string SapPlanId) {
            object[] results = this.Invoke("OTSCancelPlan", new object[] {
                        SapPlanId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OTSCancelPlanAsync(string SapPlanId) {
            this.OTSCancelPlanAsync(SapPlanId, null);
        }
        
        /// <remarks/>
        public void OTSCancelPlanAsync(string SapPlanId, object userState) {
            if ((this.OTSCancelPlanOperationCompleted == null)) {
                this.OTSCancelPlanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOTSCancelPlanOperationCompleted);
            }
            this.InvokeAsync("OTSCancelPlan", new object[] {
                        SapPlanId}, this.OTSCancelPlanOperationCompleted, userState);
        }
        
        private void OnOTSCancelPlanOperationCompleted(object arg) {
            if ((this.OTSCancelPlanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OTSCancelPlanCompleted(this, new OTSCancelPlanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/OTSUpdClosePlan", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OTSUpdClosePlan(string SapPlanId) {
            object[] results = this.Invoke("OTSUpdClosePlan", new object[] {
                        SapPlanId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OTSUpdClosePlanAsync(string SapPlanId) {
            this.OTSUpdClosePlanAsync(SapPlanId, null);
        }
        
        /// <remarks/>
        public void OTSUpdClosePlanAsync(string SapPlanId, object userState) {
            if ((this.OTSUpdClosePlanOperationCompleted == null)) {
                this.OTSUpdClosePlanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOTSUpdClosePlanOperationCompleted);
            }
            this.InvokeAsync("OTSUpdClosePlan", new object[] {
                        SapPlanId}, this.OTSUpdClosePlanOperationCompleted, userState);
        }
        
        private void OnOTSUpdClosePlanOperationCompleted(object arg) {
            if ((this.OTSUpdClosePlanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OTSUpdClosePlanCompleted(this, new OTSUpdClosePlanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/OTSRecvDebtInfo", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OTSRecvDebtInfo(string strXml) {
            object[] results = this.Invoke("OTSRecvDebtInfo", new object[] {
                        strXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OTSRecvDebtInfoAsync(string strXml) {
            this.OTSRecvDebtInfoAsync(strXml, null);
        }
        
        /// <remarks/>
        public void OTSRecvDebtInfoAsync(string strXml, object userState) {
            if ((this.OTSRecvDebtInfoOperationCompleted == null)) {
                this.OTSRecvDebtInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOTSRecvDebtInfoOperationCompleted);
            }
            this.InvokeAsync("OTSRecvDebtInfo", new object[] {
                        strXml}, this.OTSRecvDebtInfoOperationCompleted, userState);
        }
        
        private void OnOTSRecvDebtInfoOperationCompleted(object arg) {
            if ((this.OTSRecvDebtInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OTSRecvDebtInfoCompleted(this, new OTSRecvDebtInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/OTSRecvCashInfo", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OTSRecvCashInfo(string strXml) {
            object[] results = this.Invoke("OTSRecvCashInfo", new object[] {
                        strXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OTSRecvCashInfoAsync(string strXml) {
            this.OTSRecvCashInfoAsync(strXml, null);
        }
        
        /// <remarks/>
        public void OTSRecvCashInfoAsync(string strXml, object userState) {
            if ((this.OTSRecvCashInfoOperationCompleted == null)) {
                this.OTSRecvCashInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOTSRecvCashInfoOperationCompleted);
            }
            this.InvokeAsync("OTSRecvCashInfo", new object[] {
                        strXml}, this.OTSRecvCashInfoOperationCompleted, userState);
        }
        
        private void OnOTSRecvCashInfoOperationCompleted(object arg) {
            if ((this.OTSRecvCashInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OTSRecvCashInfoCompleted(this, new OTSRecvCashInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/OTSCheckDOExists", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OTSCheckDOExists(string do_id) {
            object[] results = this.Invoke("OTSCheckDOExists", new object[] {
                        do_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OTSCheckDOExistsAsync(string do_id) {
            this.OTSCheckDOExistsAsync(do_id, null);
        }
        
        /// <remarks/>
        public void OTSCheckDOExistsAsync(string do_id, object userState) {
            if ((this.OTSCheckDOExistsOperationCompleted == null)) {
                this.OTSCheckDOExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOTSCheckDOExistsOperationCompleted);
            }
            this.InvokeAsync("OTSCheckDOExists", new object[] {
                        do_id}, this.OTSCheckDOExistsOperationCompleted, userState);
        }
        
        private void OnOTSCheckDOExistsOperationCompleted(object arg) {
            if ((this.OTSCheckDOExistsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OTSCheckDOExistsCompleted(this, new OTSCheckDOExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/OTSCheckShipToFileExists", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OTSCheckShipToFileExists() {
            object[] results = this.Invoke("OTSCheckShipToFileExists", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OTSCheckShipToFileExistsAsync() {
            this.OTSCheckShipToFileExistsAsync(null);
        }
        
        /// <remarks/>
        public void OTSCheckShipToFileExistsAsync(object userState) {
            if ((this.OTSCheckShipToFileExistsOperationCompleted == null)) {
                this.OTSCheckShipToFileExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOTSCheckShipToFileExistsOperationCompleted);
            }
            this.InvokeAsync("OTSCheckShipToFileExists", new object[0], this.OTSCheckShipToFileExistsOperationCompleted, userState);
        }
        
        private void OnOTSCheckShipToFileExistsOperationCompleted(object arg) {
            if ((this.OTSCheckShipToFileExistsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OTSCheckShipToFileExistsCompleted(this, new OTSCheckShipToFileExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/TestOTSShipTo", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestOTSShipTo() {
            object[] results = this.Invoke("TestOTSShipTo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestOTSShipToAsync() {
            this.TestOTSShipToAsync(null);
        }
        
        /// <remarks/>
        public void TestOTSShipToAsync(object userState) {
            if ((this.TestOTSShipToOperationCompleted == null)) {
                this.TestOTSShipToOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOTSShipToOperationCompleted);
            }
            this.InvokeAsync("TestOTSShipTo", new object[0], this.TestOTSShipToOperationCompleted, userState);
        }
        
        private void OnTestOTSShipToOperationCompleted(object arg) {
            if ((this.TestOTSShipToCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestOTSShipToCompleted(this, new TestOTSShipToCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/TestOTSDO", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestOTSDO() {
            object[] results = this.Invoke("TestOTSDO", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestOTSDOAsync() {
            this.TestOTSDOAsync(null);
        }
        
        /// <remarks/>
        public void TestOTSDOAsync(object userState) {
            if ((this.TestOTSDOOperationCompleted == null)) {
                this.TestOTSDOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOTSDOOperationCompleted);
            }
            this.InvokeAsync("TestOTSDO", new object[0], this.TestOTSDOOperationCompleted, userState);
        }
        
        private void OnTestOTSDOOperationCompleted(object arg) {
            if ((this.TestOTSDOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestOTSDOCompleted(this, new TestOTSDOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/TestPlanning", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestPlanning() {
            object[] results = this.Invoke("TestPlanning", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestPlanningAsync() {
            this.TestPlanningAsync(null);
        }
        
        /// <remarks/>
        public void TestPlanningAsync(object userState) {
            if ((this.TestPlanningOperationCompleted == null)) {
                this.TestPlanningOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestPlanningOperationCompleted);
            }
            this.InvokeAsync("TestPlanning", new object[0], this.TestPlanningOperationCompleted, userState);
        }
        
        private void OnTestPlanningOperationCompleted(object arg) {
            if ((this.TestPlanningCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestPlanningCompleted(this, new TestPlanningCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/TestOTSRecvDebtInfo", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestOTSRecvDebtInfo() {
            object[] results = this.Invoke("TestOTSRecvDebtInfo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestOTSRecvDebtInfoAsync() {
            this.TestOTSRecvDebtInfoAsync(null);
        }
        
        /// <remarks/>
        public void TestOTSRecvDebtInfoAsync(object userState) {
            if ((this.TestOTSRecvDebtInfoOperationCompleted == null)) {
                this.TestOTSRecvDebtInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOTSRecvDebtInfoOperationCompleted);
            }
            this.InvokeAsync("TestOTSRecvDebtInfo", new object[0], this.TestOTSRecvDebtInfoOperationCompleted, userState);
        }
        
        private void OnTestOTSRecvDebtInfoOperationCompleted(object arg) {
            if ((this.TestOTSRecvDebtInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestOTSRecvDebtInfoCompleted(this, new TestOTSRecvDebtInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/TestOTSRecvCashInfo", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestOTSRecvCashInfo() {
            object[] results = this.Invoke("TestOTSRecvCashInfo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestOTSRecvCashInfoAsync() {
            this.TestOTSRecvCashInfoAsync(null);
        }
        
        /// <remarks/>
        public void TestOTSRecvCashInfoAsync(object userState) {
            if ((this.TestOTSRecvCashInfoOperationCompleted == null)) {
                this.TestOTSRecvCashInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOTSRecvCashInfoOperationCompleted);
            }
            this.InvokeAsync("TestOTSRecvCashInfo", new object[0], this.TestOTSRecvCashInfoOperationCompleted, userState);
        }
        
        private void OnTestOTSRecvCashInfoOperationCompleted(object arg) {
            if ((this.TestOTSRecvCashInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestOTSRecvCashInfoCompleted(this, new TestOTSRecvCashInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/TestAdjustRoute", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestAdjustRoute() {
            object[] results = this.Invoke("TestAdjustRoute", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestAdjustRouteAsync() {
            this.TestAdjustRouteAsync(null);
        }
        
        /// <remarks/>
        public void TestAdjustRouteAsync(object userState) {
            if ((this.TestAdjustRouteOperationCompleted == null)) {
                this.TestAdjustRouteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestAdjustRouteOperationCompleted);
            }
            this.InvokeAsync("TestAdjustRoute", new object[0], this.TestAdjustRouteOperationCompleted, userState);
        }
        
        private void OnTestAdjustRouteOperationCompleted(object arg) {
            if ((this.TestAdjustRouteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestAdjustRouteCompleted(this, new TestAdjustRouteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/TestShipToRequest", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestShipToRequest() {
            object[] results = this.Invoke("TestShipToRequest", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestShipToRequestAsync() {
            this.TestShipToRequestAsync(null);
        }
        
        /// <remarks/>
        public void TestShipToRequestAsync(object userState) {
            if ((this.TestShipToRequestOperationCompleted == null)) {
                this.TestShipToRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestShipToRequestOperationCompleted);
            }
            this.InvokeAsync("TestShipToRequest", new object[0], this.TestShipToRequestOperationCompleted, userState);
        }
        
        private void OnTestShipToRequestOperationCompleted(object arg) {
            if ((this.TestShipToRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestShipToRequestCompleted(this, new TestShipToRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.onelink.co.th/DHMService/TestAssignVehicle", RequestNamespace="http://www.onelink.co.th/DHMService", ResponseNamespace="http://www.onelink.co.th/DHMService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestAssignVehicle() {
            object[] results = this.Invoke("TestAssignVehicle", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestAssignVehicleAsync() {
            this.TestAssignVehicleAsync(null);
        }
        
        /// <remarks/>
        public void TestAssignVehicleAsync(object userState) {
            if ((this.TestAssignVehicleOperationCompleted == null)) {
                this.TestAssignVehicleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestAssignVehicleOperationCompleted);
            }
            this.InvokeAsync("TestAssignVehicle", new object[0], this.TestAssignVehicleOperationCompleted, userState);
        }
        
        private void OnTestAssignVehicleOperationCompleted(object arg) {
            if ((this.TestAssignVehicleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestAssignVehicleCompleted(this, new TestAssignVehicleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OTSReceiveShipToCompletedEventHandler(object sender, OTSReceiveShipToCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OTSReceiveShipToCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OTSReceiveShipToCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OTSReceiveShipToFromSAPCompletedEventHandler(object sender, OTSReceiveShipToFromSAPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OTSReceiveShipToFromSAPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OTSReceiveShipToFromSAPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OTSReciveQDataCompletedEventHandler(object sender, OTSReciveQDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OTSReciveQDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OTSReciveQDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OTSReciveValueFuelCompletedEventHandler(object sender, OTSReciveValueFuelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OTSReciveValueFuelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OTSReciveValueFuelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OTSReciveRealFuelCompletedEventHandler(object sender, OTSReciveRealFuelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OTSReciveRealFuelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OTSReciveRealFuelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OTSReciveCostPerDistanceCompletedEventHandler(object sender, OTSReciveCostPerDistanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OTSReciveCostPerDistanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OTSReciveCostPerDistanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OTSCheckPlanStatusCompletedEventHandler(object sender, OTSCheckPlanStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OTSCheckPlanStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OTSCheckPlanStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OTSReciveQDriverCompletedEventHandler(object sender, OTSReciveQDriverCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OTSReciveQDriverCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OTSReciveQDriverCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OTSCancelQDataCompletedEventHandler(object sender, OTSCancelQDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OTSCancelQDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OTSCancelQDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OTSReqCustomDistanceCompletedEventHandler(object sender, OTSReqCustomDistanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OTSReqCustomDistanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OTSReqCustomDistanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OTSReqShipToDistanceCompletedEventHandler(object sender, OTSReqShipToDistanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OTSReqShipToDistanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OTSReqShipToDistanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OTSPlanningCompletedEventHandler(object sender, OTSPlanningCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OTSPlanningCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OTSPlanningCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OTSAdjustPlanningCompletedEventHandler(object sender, OTSAdjustPlanningCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OTSAdjustPlanningCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OTSAdjustPlanningCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OTSAssignVehicleCompletedEventHandler(object sender, OTSAssignVehicleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OTSAssignVehicleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OTSAssignVehicleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OTSCancelPlanCompletedEventHandler(object sender, OTSCancelPlanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OTSCancelPlanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OTSCancelPlanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OTSUpdClosePlanCompletedEventHandler(object sender, OTSUpdClosePlanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OTSUpdClosePlanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OTSUpdClosePlanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OTSRecvDebtInfoCompletedEventHandler(object sender, OTSRecvDebtInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OTSRecvDebtInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OTSRecvDebtInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OTSRecvCashInfoCompletedEventHandler(object sender, OTSRecvCashInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OTSRecvCashInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OTSRecvCashInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OTSCheckDOExistsCompletedEventHandler(object sender, OTSCheckDOExistsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OTSCheckDOExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OTSCheckDOExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void OTSCheckShipToFileExistsCompletedEventHandler(object sender, OTSCheckShipToFileExistsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OTSCheckShipToFileExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OTSCheckShipToFileExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void TestOTSShipToCompletedEventHandler(object sender, TestOTSShipToCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestOTSShipToCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestOTSShipToCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void TestOTSDOCompletedEventHandler(object sender, TestOTSDOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestOTSDOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestOTSDOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void TestPlanningCompletedEventHandler(object sender, TestPlanningCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestPlanningCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestPlanningCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void TestOTSRecvDebtInfoCompletedEventHandler(object sender, TestOTSRecvDebtInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestOTSRecvDebtInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestOTSRecvDebtInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void TestOTSRecvCashInfoCompletedEventHandler(object sender, TestOTSRecvCashInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestOTSRecvCashInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestOTSRecvCashInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void TestAdjustRouteCompletedEventHandler(object sender, TestAdjustRouteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestAdjustRouteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestAdjustRouteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void TestShipToRequestCompletedEventHandler(object sender, TestShipToRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestShipToRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestShipToRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void TestAssignVehicleCompletedEventHandler(object sender, TestAssignVehicleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestAssignVehicleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestAssignVehicleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591