using System;
using System.Data;
using SourceCode.SmartObjects.Client;
using SourceCode.Hosting.Client.BaseAPI;
using System.Text;
using System.Data.Common;
using System.IO;
using System.Xml.XPath;


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     .Net class implementation for SmartObject ZHANDHELD_GR_COUNT_GOODSMVT_HEADRET.
//     Changes to this file may cause incorrect behavior
// </auto-generated>
//------------------------------------------------------------------------------

    
namespace  SmartObjects
{

    public class ZHANDHELD_GR_COUNT_GOODSMVT_HEADRET : ZHANDHELD_GR_COUNT_GOODSMVT_HEADRET_properties
    {
        #region Fields (4)

        private readonly string _connectionString;
        private SmartObject _smartObject;
        private const string cHOST = "192.168.0.159";
        private const uint cPORT = 5555;

        #endregion Fields

        #region Constructors (2)

        public ZHANDHELD_GR_COUNT_GOODSMVT_HEADRET(string connectionString)
        {
            _connectionString = connectionString;
            this.GetSmartObject();
        }
        public ZHANDHELD_GR_COUNT_GOODSMVT_HEADRET()
        {
            SCConnectionStringBuilder hostServerConnectionString = new SCConnectionStringBuilder();
            hostServerConnectionString.Host = cHOST;
            hostServerConnectionString.Port = cPORT;
            hostServerConnectionString.IsPrimaryLogin = true;
            hostServerConnectionString.Integrated = true;
            _connectionString = hostServerConnectionString.ConnectionString;
            this.GetSmartObject();
        }

        #endregion Constructors

        #region Methods (13)

        // Public Methods (7) 

        public ZHANDHELD_GR_COUNT_GOODSMVT_HEADRET_properties Serialize()
        {

            // Set method to execute
            _smartObject.MethodToExecute = "Serialize";

            // Assign Input properties
                SetPropertyValue(_smartObject.Methods["Serialize"].InputProperties["MAT_DOC"],MAT_DOC);
                SetPropertyValue(_smartObject.Methods["Serialize"].InputProperties["DOC_YEAR"],DOC_YEAR);

            try
            {
                SmartObjectClientServer soServer = CreateConnection();
                SmartObject returnSmartObject;

                // Execute SmartObject
                using (soServer.Connection)
                {
                    returnSmartObject = soServer.ExecuteScalar(_smartObject);
                }
                // Assign Return properties
                ZHANDHELD_GR_COUNT_GOODSMVT_HEADRET_properties returnProperties = GetPropertiesObject();
                returnProperties.Serialized_Item__GOODSMVT_HEADRET_ = SetProperty_Serialized_Item__GOODSMVT_HEADRET_(returnSmartObject.Properties["Serialized_Item__GOODSMVT_HEADRET_"].Value);
                return returnProperties;

            }
            catch (Exception ex)
            {
                throw DisplayError(ex);
            }
            finally
            {
                ClearProperties();
            }
        }

        public ZHANDHELD_GR_COUNT_GOODSMVT_HEADRET_properties Deserialize()
        {

            // Set method to execute
            _smartObject.MethodToExecute = "Deserialize";

            // Assign Input properties
                SetPropertyValue(_smartObject.Methods["Deserialize"].InputProperties["Serialized_Item__GOODSMVT_HEADRET_"],Serialized_Item__GOODSMVT_HEADRET_);

            try
            {
                SmartObjectClientServer soServer = CreateConnection();
                SmartObject returnSmartObject;

                // Execute SmartObject
                using (soServer.Connection)
                {
                    returnSmartObject = soServer.ExecuteScalar(_smartObject);
                }
                // Assign Return properties
                ZHANDHELD_GR_COUNT_GOODSMVT_HEADRET_properties returnProperties = GetPropertiesObject();
                returnProperties.MAT_DOC = SetProperty_MAT_DOC(returnSmartObject.Properties["MAT_DOC"].Value);
                returnProperties.DOC_YEAR = SetProperty_DOC_YEAR(returnSmartObject.Properties["DOC_YEAR"].Value);
                return returnProperties;

            }
            catch (Exception ex)
            {
                throw DisplayError(ex);
            }
            finally
            {
                ClearProperties();
            }
        }

        public ZHANDHELD_GR_COUNT_GOODSMVT_HEADRET_properties SerializeAddItemToArray()
        {

            // Set method to execute
            _smartObject.MethodToExecute = "SerializeAddItemToArray";

            // Assign Input properties
                SetPropertyValue(_smartObject.Methods["SerializeAddItemToArray"].InputProperties["Serialized_Array__GOODSMVT_HEADRET___"],Serialized_Array__GOODSMVT_HEADRET___);
                SetPropertyValue(_smartObject.Methods["SerializeAddItemToArray"].InputProperties["MAT_DOC"],MAT_DOC);
                SetPropertyValue(_smartObject.Methods["SerializeAddItemToArray"].InputProperties["DOC_YEAR"],DOC_YEAR);

            try
            {
                SmartObjectClientServer soServer = CreateConnection();
                SmartObject returnSmartObject;

                // Execute SmartObject
                using (soServer.Connection)
                {
                    returnSmartObject = soServer.ExecuteScalar(_smartObject);
                }
                // Assign Return properties
                ZHANDHELD_GR_COUNT_GOODSMVT_HEADRET_properties returnProperties = GetPropertiesObject();
                returnProperties.Serialized_Array__GOODSMVT_HEADRET___ = SetProperty_Serialized_Array__GOODSMVT_HEADRET___(returnSmartObject.Properties["Serialized_Array__GOODSMVT_HEADRET___"].Value);
                return returnProperties;

            }
            catch (Exception ex)
            {
                throw DisplayError(ex);
            }
            finally
            {
                ClearProperties();
            }
        }

        public DataTable DeserializeArray()        {

            // Set method to execute
            _smartObject.MethodToExecute = "DeserializeArray";

            // Assign Input properties
            if (Serialized_Array__GOODSMVT_HEADRET___ != null)
            {
                SetPropertyValue(_smartObject.ListMethods["DeserializeArray"].InputProperties["Serialized_Array__GOODSMVT_HEADRET___"],Serialized_Array__GOODSMVT_HEADRET___);
            }

            try
            {
                SmartObjectClientServer soServer = CreateConnection();

                // Execute SmartObject
                using (soServer.Connection)
                {
                    return soServer.ExecuteListDataTable(_smartObject);
                }

            }
            catch (Exception ex)
            {
                throw DisplayError(ex);
            }
            finally
            {
                ClearProperties();
            }
        }

        public DbDataReader DeserializeArray_Reader()        {

            // Set method to execute
            _smartObject.MethodToExecute = "DeserializeArray";

            // Assign Input properties
            if (Serialized_Array__GOODSMVT_HEADRET___ != null)
            {
                SetPropertyValue(_smartObject.ListMethods["DeserializeArray"].InputProperties["Serialized_Array__GOODSMVT_HEADRET___"],Serialized_Array__GOODSMVT_HEADRET___);
            }

            try
            {
                SmartObjectClientServer soServer = CreateConnection();

                // Execute SmartObject
                using (soServer.Connection)
                {
                    return soServer.ExecuteListReader(_smartObject);
                }

            }
            catch (Exception ex)
            {
                throw DisplayError(ex);
            }
            finally
            {
                ClearProperties();
            }
        }


        public DataTable DeserializeTypedArray()        {

            // Set method to execute
            _smartObject.MethodToExecute = "DeserializeTypedArray";

            // Assign Input properties
            if (Serialized_Array__GOODSMVT_HEADRET___ != null)
            {
                SetPropertyValue(_smartObject.ListMethods["DeserializeTypedArray"].InputProperties["Serialized_Array__GOODSMVT_HEADRET___"],Serialized_Array__GOODSMVT_HEADRET___);
            }

            try
            {
                SmartObjectClientServer soServer = CreateConnection();

                // Execute SmartObject
                using (soServer.Connection)
                {
                    return soServer.ExecuteListDataTable(_smartObject);
                }

            }
            catch (Exception ex)
            {
                throw DisplayError(ex);
            }
            finally
            {
                ClearProperties();
            }
        }

        public DbDataReader DeserializeTypedArray_Reader()        {

            // Set method to execute
            _smartObject.MethodToExecute = "DeserializeTypedArray";

            // Assign Input properties
            if (Serialized_Array__GOODSMVT_HEADRET___ != null)
            {
                SetPropertyValue(_smartObject.ListMethods["DeserializeTypedArray"].InputProperties["Serialized_Array__GOODSMVT_HEADRET___"],Serialized_Array__GOODSMVT_HEADRET___);
            }

            try
            {
                SmartObjectClientServer soServer = CreateConnection();

                // Execute SmartObject
                using (soServer.Connection)
                {
                    return soServer.ExecuteListReader(_smartObject);
                }

            }
            catch (Exception ex)
            {
                throw DisplayError(ex);
            }
            finally
            {
                ClearProperties();
            }
        }


        // Private Methods (6) 

        private void ClearProperties()
        {
            foreach (SmartProperty property in _smartObject.Properties)
            {
                property.Clear();
                property.ValueBehaviour = ValueBehaviour.None;
            }
        }

        private SmartObjectClientServer CreateConnection()
        {
            SmartObjectClientServer soServer = new SmartObjectClientServer();
            soServer.CreateConnection();
            soServer.Connection.Open(_connectionString);
            return soServer;
        }

        private Exception DisplayError(Exception ex)
        {
            if (ex is SmartObjectException)
            {
                return DisplayError(ex as SmartObjectException);
            }
            else
            {
                return ex;
            }
        }

        private Exception DisplayError(SmartObjectException smartObjectException)
        {
            StringBuilder errorMessage = new StringBuilder();
            foreach (SmartObjectExceptionData smartobjectExceptionData in smartObjectException.BrokerData)
            {
                string message = smartobjectExceptionData.Message;
                string service = smartobjectExceptionData.ServiceName;
                string serviceGuid = smartobjectExceptionData.ServiceGuid;
                string severity = smartobjectExceptionData.Severity.ToString();
                string innermessage = smartobjectExceptionData.InnerExceptionMessage;
                errorMessage.AppendLine(message);
                errorMessage.AppendLine();
                errorMessage.AppendLine("Service: " + service);
                errorMessage.AppendLine("Service Guid: " + serviceGuid);
                errorMessage.AppendLine("Severity: " + severity);
                if (!string.IsNullOrEmpty(innermessage))
                {
                    errorMessage.AppendLine("InnerException Message: " + innermessage);
                }
            }
            return new Exception(errorMessage.ToString());
        }

        private void GetSmartObject()
        {
            SmartObjectClientServer clientServer = CreateConnection();
            using (clientServer.Connection)
            {
                _smartObject = clientServer.GetSmartObject("ZHANDHELD_GR_COUNT_GOODSMVT_HEADRET");
            }
        }

  private static void SetPropertyValue(SmartProperty smartProperty, object value)
        {
            if (value == null)
            {
                smartProperty.ValueBehaviour = ValueBehaviour.Unchanged;
                smartProperty.Value = null;
            }
            else if (value == DBNull.Value)
            {
                smartProperty.ValueBehaviour = ValueBehaviour.Clear;
                smartProperty.Value = null;
            }
            else if (value.ToString() == string.Empty)
            {
                smartProperty.ValueBehaviour = ValueBehaviour.Empty;
                smartProperty.Value = string.Empty;
            }
            else
            {
                smartProperty.ValueBehaviour = ValueBehaviour.None;
                smartProperty.Value = value.ToString();
            }
        }

        #endregion Methods
    }

 public class ZHANDHELD_GR_COUNT_GOODSMVT_HEADRET_properties
    {
        #region Fields (4)

        private string _MAT_DOC;
        private int? _DOC_YEAR;
        private string _Serialized_Item__GOODSMVT_HEADRET_;
        private string _Serialized_Array__GOODSMVT_HEADRET___;

        #endregion Fields

        #region Constructors (1)

        protected ZHANDHELD_GR_COUNT_GOODSMVT_HEADRET_properties()
        {
        }

        #endregion Constructors

        #region Properties (4)

        public string MAT_DOC
        {
            get
            {
                return _MAT_DOC;
            }
            set
            {
                _MAT_DOC = value;
            }
        }

        public int? DOC_YEAR
        {
            get
            {
                return _DOC_YEAR;
            }
            set
            {
                _DOC_YEAR = value;
            }
        }

        public string Serialized_Item__GOODSMVT_HEADRET_
        {
            get
            {
                return _Serialized_Item__GOODSMVT_HEADRET_;
            }
            set
            {
                _Serialized_Item__GOODSMVT_HEADRET_ = value;
            }
        }

        public string Serialized_Array__GOODSMVT_HEADRET___
        {
            get
            {
                return _Serialized_Array__GOODSMVT_HEADRET___;
            }
            set
            {
                _Serialized_Array__GOODSMVT_HEADRET___ = value;
            }
        }


        #endregion Properties

        #region Methods (5)

        // Protected Methods (5) 
        protected ZHANDHELD_GR_COUNT_GOODSMVT_HEADRET_properties GetPropertiesObject()
        {
            return new ZHANDHELD_GR_COUNT_GOODSMVT_HEADRET_properties();
        }

        protected static string SetProperty_MAT_DOC(string MAT_DOC)
        {
                        if(MAT_DOC == null)
            {
                return null;
            }


            if(MAT_DOC == string.Empty)
            {
                return null;
            }

            return MAT_DOC;
        }

        protected static int? SetProperty_DOC_YEAR(string DOC_YEAR)
        {
                        if(DOC_YEAR == null)
            {
                return null;
            }


            if(DOC_YEAR == string.Empty)
            {
                return null;
            }

            return int.Parse(DOC_YEAR);
        }

        protected static string SetProperty_Serialized_Item__GOODSMVT_HEADRET_(string Serialized_Item__GOODSMVT_HEADRET_)
        {
                        if(Serialized_Item__GOODSMVT_HEADRET_ == null)
            {
                return null;
            }


            if(Serialized_Item__GOODSMVT_HEADRET_ == string.Empty)
            {
                return null;
            }

            return Serialized_Item__GOODSMVT_HEADRET_;
        }

        protected static string SetProperty_Serialized_Array__GOODSMVT_HEADRET___(string Serialized_Array__GOODSMVT_HEADRET___)
        {
                        if(Serialized_Array__GOODSMVT_HEADRET___ == null)
            {
                return null;
            }


            if(Serialized_Array__GOODSMVT_HEADRET___ == string.Empty)
            {
                return null;
            }

            return Serialized_Array__GOODSMVT_HEADRET___;
        }


        #endregion Methods

    }

   #region Object Classes

    public abstract class NamedObject
    {

        #region Fields (3)

        private string _name;
        private string _value;
        protected const string SCNULL = "scnull";

        #endregion Fields

        #region Constructors (2)

        public NamedObject(string name, string value)
        {
            _name = name;
            _value = value;
        }

        public NamedObject(string inputValue)
        {
            this.FromValue(inputValue);
        }

        #endregion Constructors

        #region Properties (2)

        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }

        public string Value
        {
            get
            {
                return _value;
            }
            set
            {
                _value = value;
            }
        }

        #endregion Properties

        #region Methods (3)

        // Public Methods (3) 

        public abstract void FromValue(string inputValue);

        public override string ToString()
        {
            return ToValue();
        }

        public abstract string ToValue();

        #endregion Methods

    }

    public class ImageObject : NamedObject
    {

        #region Constructors (2)

        public ImageObject(string name, string value)
            : base(name, value)
        {
        }

        public ImageObject(string inputValue)
            : base(inputValue)
        {
        }

        #endregion Constructors

        #region Methods (2)

        // Public Methods (2) 
        public override void FromValue(string inputValue)
        {
            if (!string.IsNullOrEmpty(inputValue))
            {
                using (StringReader reader = new StringReader(inputValue))
                {
                    XPathDocument xDoc = new XPathDocument(reader);
                    XPathNavigator xNav = xDoc.CreateNavigator();
                    string imageNameValue = xNav.SelectSingleNode("image/name").InnerXml;
                    string contentValue = xNav.SelectSingleNode("image/content").InnerXml;
                    if (imageNameValue == SCNULL)
                        this.Name = string.Empty;
                    else
                        this.Name = imageNameValue;
                    if (contentValue == SCNULL)
                        this.Value = string.Empty;
                    else
                        this.Value = contentValue;
                }
            }
            else
            {
                this.Value = string.Empty;
                this.Name = string.Empty;
            }
        }

        public override string ToValue()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("<image>");
            if (this.Name == null)
            {
                sb.Append("<name/>");
            }
            else
            {
                sb.Append("<name>");
                sb.Append(this.Name);
                sb.Append("</name>");
            }
            if (this.Value == null)
            {
                sb.Append("<content/>");
            }
            else
            {
                sb.Append("<content>");
                sb.Append(this.Value);
                sb.Append("</content>");
            }
            sb.Append("</image>");
            return sb.ToString();
        }

        #endregion Methods

    }

    public class FileObject : NamedObject
    {

        #region Constructors (2)

        public FileObject(string name, string value)
            : base(name, value)
        {
        }

        public FileObject(string inputValue)
            : base(inputValue)
        {
        }

        #endregion Constructors

        #region Methods (2)

        // Public Methods (2) 
        public override void FromValue(string inputValue)
        {
            if (!string.IsNullOrEmpty(inputValue))
            {
                using (StringReader reader = new StringReader(inputValue))
                {
                    XPathDocument xDoc = new XPathDocument(reader);
                    XPathNavigator xNav = xDoc.CreateNavigator();
                    string fileNameValue = xNav.SelectSingleNode("file/name").InnerXml;
                    string contentValue = xNav.SelectSingleNode("file/content").InnerXml;
                    if (fileNameValue == SCNULL)
                        this.Name = string.Empty;
                    else
                        this.Name = fileNameValue;
                    if (contentValue == SCNULL)
                        this.Value = string.Empty;
                    else
                        this.Value = contentValue;
                }
            }
            else
            {
                this.Value = string.Empty;
                this.Name = string.Empty;
            }
        }

        public override string ToValue()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("<file>");
            if (this.Name == null)
            {
                sb.Append("<name/>");
            }
            else
            {
                sb.Append("<name>");
                sb.Append(this.Name);
                sb.Append("</name>");
            }
            if (this.Value == null)
            {
                sb.Append("<content/>");
            }
            else
            {
                sb.Append("<content>");
                sb.Append(this.Value);
                sb.Append("</content>");
            }
            sb.Append("</file>");
            return sb.ToString();
        }

        #endregion Methods

    }

    public class HyperLinkObject : NamedObject
    {

        #region Constructors (2)

        public HyperLinkObject(string name, string value)
            : base(name, value)
        {
        }

        public HyperLinkObject(string inputValue)
            : base(inputValue)
        {
        }

        #endregion Constructors

        #region Methods (2)

        // Public Methods (2) 

        public override void FromValue(string inputValue)
        {
            if (!string.IsNullOrEmpty(inputValue))
            {
                using (StringReader reader = new StringReader(inputValue))
                {
                    XPathDocument xDoc = new XPathDocument(reader);
                    XPathNavigator xNav = xDoc.CreateNavigator();
                    string hyperLinkNameValue = xNav.SelectSingleNode("hyperlink/display").InnerXml;
                    string contentValue = xNav.SelectSingleNode("hyperlink/link").InnerXml;
                    if (hyperLinkNameValue == SCNULL)
                        this.Name = string.Empty;
                    else
                        this.Name = hyperLinkNameValue;
                    if (contentValue == SCNULL)
                        this.Value = string.Empty;
                    else
                        this.Value = contentValue;
                }
            }
            else
            {
                this.Value = string.Empty;
                this.Name = string.Empty;
            }
        }

        public override string ToValue()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("<hyperlink>");
            if (this.Name == null)
            {
                sb.Append("<link/>");
            }
            else
            {
                sb.Append("<link>");
                sb.Append(this.Name);
                sb.Append("</link>");
            }
            if (this.Value == null)
            {
                sb.Append("<display/>");
            }
            else
            {
                sb.Append("<display>");
                sb.Append(this.Value);
                sb.Append("</display>");
            }
            sb.Append("</hyperlink>");
            return sb.ToString();
        }

        #endregion Methods

    }

    #endregion
}
